// Figure data for the vLLM and SGLang posts: process diagrams for BoxDiagram and request
// lifecycles for SequenceSteps. Every step names the function that does the work, at the pinned
// commits cited in the posts.
import type { BoxEdge, BoxNode } from "../payments/boxDiagram";
import type { Message, Participant } from "../payments/sequence";

// ---------------------------------------------------------------- vLLM

export const vllmNodes: BoxNode[] = [
	{ id: "fe", label: "API server process", col: 1, row: 0, h: 3, group: -1 },
	{
		id: "core",
		label: "EngineCore process",
		col: 2,
		row: 0,
		w: 2,
		h: 3,
		group: -1,
	},
	{ id: "wk", label: "one process per GPU", col: 4, row: 0, h: 3, group: -1 },
	{
		id: "client",
		label: "Client",
		sub: "HTTP / OpenAI API",
		col: 0,
		row: 1,
		group: 0,
		note: "Sends an OpenAI-style request, for example POST /v1/chat/completions, and reads the reply as a stream of server-sent events.",
	},
	{
		id: "api",
		label: "OpenAI server",
		sub: "FastAPI routes",
		col: 1,
		row: 0,
		group: 1,
		note: "The serving layer (vllm/entrypoints/openai/) validates the request, renders the chat template and calls <code>engine_client.generate()</code>. Several API server processes can share one engine.",
	},
	{
		id: "async",
		label: "AsyncLLM",
		sub: "renderer, detokenize",
		col: 1,
		row: 1,
		group: 1,
		note: "The renderer applies the chat template, tokenizes and preprocesses images. <code>AsyncLLM.add_request()</code> turns the result into an <code>EngineCoreRequest</code> (token ids, sampling parameters, image features) with the InputProcessor and sends it to the engine core. A background <code>output_handler</code> task pulls outputs back, and the OutputProcessor detokenizes them incrementally and checks stop strings.",
	},
	{
		id: "in",
		label: "input thread",
		sub: "ZMQ DEALER",
		col: 2,
		row: 0,
		group: 2,
		note: "<code>EngineCoreProc.process_input_sockets()</code> runs in its own thread: it decodes msgpack messages from the front ends and puts them on <code>input_queue</code>, so socket I/O and deserialisation never block the scheduling loop.",
	},
	{
		id: "sched",
		label: "Scheduler",
		sub: "token budget per step",
		col: 2,
		row: 1,
		group: 2,
		note: "<code>EngineCoreProc.run_busy_loop()</code> drains <code>input_queue</code> and calls <code>step()</code>: <code>Scheduler.schedule()</code> picks how many tokens each request computes this step, the executor runs the model, and <code>update_from_output()</code> appends the sampled tokens and finishes requests.",
	},
	{
		id: "kvm",
		label: "KVCacheManager",
		sub: "block pool, prefix cache",
		col: 3,
		row: 1,
		group: 2,
		note: "Owns the block pool: which physical blocks each request holds, their reference counts and the hash table of cached full blocks. It only does bookkeeping; the KV tensors live on the GPUs.",
	},
	{
		id: "exec",
		label: "MultiprocExecutor",
		sub: "shared-memory queue",
		col: 3,
		row: 0,
		group: 2,
		note: "Broadcasts each <code>SchedulerOutput</code> to every worker through a shared-memory <code>MessageQueue</code> and collects the <code>ModelRunnerOutput</code> from the rank that samples.",
	},
	{
		id: "out",
		label: "output thread",
		sub: "ZMQ PUSH",
		col: 2,
		row: 2,
		group: 2,
		note: "<code>process_output_sockets()</code> serialises <code>EngineCoreOutputs</code> (new token ids per request, finish reasons, stats) and pushes them back to the API server.",
	},
	{
		id: "w0",
		label: "GPU worker 0",
		sub: "GPUModelRunner",
		col: 4,
		row: 0,
		group: 3,
		note: "Each worker owns one GPU: the model weights for its tensor-parallel shard, its share of every layer's KV cache, and a model runner that turns a <code>SchedulerOutput</code> into input tensors, block tables and slot mappings, runs the forward pass (usually by replaying a CUDA graph) and samples.",
	},
	{
		id: "w1",
		label: "GPU worker 1",
		sub: "GPUModelRunner",
		col: 4,
		row: 1,
		group: 3,
		note: "Workers of a tensor-parallel group run the same step in lockstep and combine partial results with all-reduce: NCCL, or vLLM's own custom all-reduce kernel for small messages over NVLink.",
	},
	{
		id: "w2",
		label: "…",
		sub: "TP × PP workers",
		col: 4,
		row: 2,
		group: 3,
	},
];

export const vllmEdges: BoxEdge[] = [
	{ from: "client", to: "api", label: "HTTP" },
	{ from: "api", to: "async" },
	{ from: "async", to: "in", label: "ZMQ" },
	{ from: "in", to: "sched" },
	{ from: "sched", to: "kvm", both: true },
	{ from: "sched", to: "exec" },
	{ from: "exec", to: "w0", both: true },
	{ from: "exec", to: "w1", both: true },
	{ from: "sched", to: "out" },
	{ from: "out", to: "async", label: "ZMQ" },
	{ from: "w0", to: "w1", both: true, dashed: true },
];

export const vllmParticipants: Participant[] = [
	{ id: "client", label: "Client" },
	{ id: "api", label: "API server", sub: "AsyncLLM" },
	{ id: "core", label: "EngineCore", sub: "Scheduler" },
	{ id: "worker", label: "GPU worker", sub: "model runner" },
];

export const vllmLifecycle: Message[] = [
	{
		from: "client",
		to: "api",
		label: "POST /v1/chat/completions",
		step: "HTTP",
		phase: "Front end",
		note: "The request arrives at the FastAPI route, which validates it and hands it to <code>OpenAIServingChat</code>.",
	},
	{
		from: "api",
		to: "api",
		label: "template, tokenize → EngineCoreRequest",
		step: "input",
		note: "The renderer applies the chat template, tokenizes on a thread pool and runs the multimodal processor on any images. <code>AsyncLLM.add_request()</code> then has the InputProcessor build an <code>EngineCoreRequest</code> and registers a per-request output queue and detokenizer with the OutputProcessor. With <code>n &gt; 1</code> it fans out one child request per sample.",
	},
	{
		from: "api",
		to: "core",
		label: "ADD (msgpack over ZMQ)",
		step: "send",
		note: "<code>AsyncMPClient.add_request_async()</code> sends the request over a ZMQ ROUTER socket. The engine core's input thread decodes it and queues it; <code>Scheduler.add_request()</code> puts it in the waiting queue.",
	},
	{
		from: "core",
		to: "core",
		label: "schedule(): blocks, budget",
		step: "schedule",
		phase: "Engine step",
		note: "<code>Scheduler.schedule()</code> serves running requests first, then admits waiting ones: it looks up the prompt's cached blocks, asks <code>allocate_slots()</code> for the rest and charges the token budget. The result is a <code>SchedulerOutput</code>: new requests, per-request token counts and new block ids.",
	},
	{
		from: "core",
		to: "worker",
		label: "SchedulerOutput",
		step: "dispatch",
		note: "The executor broadcasts the <code>SchedulerOutput</code> to every worker through shared memory; only the diff since the previous step travels, because workers keep the request state.",
	},
	{
		from: "worker",
		to: "worker",
		label: "forward",
		step: "forward",
		note: "The model runner applies the diff to its persistent batch, builds the flat token and position tensors, block tables and slot mapping on the GPU, runs the model (each attention layer first writes its new K and V at the slot mapping, then attends through the block table) and samples.",
	},
	{
		from: "worker",
		to: "core",
		label: "ModelRunnerOutput",
		step: "result",
		reply: true,
		note: "The sampled token ids (plus logprobs if asked for) come back to the engine core.",
	},
	{
		from: "core",
		to: "core",
		label: "update_from_output()",
		step: "update",
		note: "The scheduler appends each new token, checks max_tokens and stop token ids, frees the blocks of finished requests and builds one <code>EngineCoreOutput</code> per request.",
	},
	{
		from: "core",
		to: "api",
		label: "EngineCoreOutputs (ZMQ)",
		step: "outputs",
		reply: true,
		phase: "Back to the client",
		note: "The output thread pushes the outputs to the API server, where the <code>output_handler</code> task picks them up.",
	},
	{
		from: "api",
		to: "api",
		label: "detokenize, stop strings",
		step: "detok",
		note: "The OutputProcessor detokenizes incrementally and checks stop strings; a request that hit one is aborted in the engine core.",
	},
	{
		from: "api",
		to: "client",
		label: "SSE chunk",
		step: "stream",
		reply: true,
		tone: 1,
		note: "The new text goes out as a server-sent event. The engine keeps stepping, and every step adds one more token to this stream until the request finishes and its blocks return to the pool.",
	},
];

// Where an image goes in vLLM: front end (fetch, HF processor, placeholder expansion), engine
// core (encoder budget, encoder cache bookkeeping, prefix-cache keys), worker (vision encoder,
// encoder cache, embedding merge).
export const vllmMmNodes: BoxNode[] = [
	{ id: "fe", label: "API server process", col: 1, row: 0, h: 3, group: -1 },
	{ id: "core", label: "EngineCore process", col: 2, row: 0, h: 3, group: -1 },
	{ id: "wk", label: "GPU worker", col: 3, row: 0, h: 3, group: -1 },
	{
		id: "req",
		label: "Chat request",
		sub: "image_url + text",
		col: 0,
		row: 0,
		group: 0,
		note: 'A message whose <code>content</code> is a list of parts, one of them <code>{"type": "image_url", "image_url": {"url": ...}}</code>. The URL can be <code>http(s)://</code>, a base64 <code>data:</code> URL or, if the server allows it, <code>file://</code>.',
	},
	{
		id: "fetch",
		label: "MediaConnector",
		sub: "fetch, decode",
		col: 1,
		row: 0,
		group: 1,
		note: "<code>parse_chat_messages_async()</code> replaces the image part with the model's placeholder and schedules <code>fetch_image_async()</code>, which downloads the bytes (5 s timeout by default) and decodes them into an RGB PIL image on a thread pool.",
	},
	{
		id: "proc",
		label: "Multimodal processor",
		sub: "resize, patches",
		col: 1,
		row: 1,
		group: 1,
		note: "After the chat template and tokenizer, <code>BaseMultiModalProcessor.apply()</code> runs the model's Hugging Face image processor (resize, normalise, cut into patches) and hashes the image. A processor cache keyed by that hash skips the work for an image seen before.",
	},
	{
		id: "upd",
		label: "Prompt update",
		sub: "1 → N placeholder tokens",
		col: 1,
		row: 2,
		group: 1,
		note: "The single placeholder token is replaced by as many copies as the vision encoder will output embeddings (1,196 for a 1280×720 image in Qwen2-VL). The result records where they are, <code>PlaceholderRange(offset=15, length=1196)</code>, and travels to the engine core in the request's <code>mm_features</code>.",
	},
	{
		id: "sched",
		label: "Scheduler",
		sub: "encoder budget",
		col: 2,
		row: 0,
		group: 2,
		note: "<code>_try_schedule_encoder_inputs()</code> runs the encoder for an image when the step's tokens reach its placeholders, if the encoder budget and encoder cache have room; otherwise the request's tokens stop just before the image.",
	},
	{
		id: "ecm",
		label: "EncoderCacheManager",
		sub: "space, by image hash",
		col: 2,
		row: 1,
		group: 2,
		note: "Bookkeeping for the encoder cache: which image hashes are stored, which requests use them, how many embedding slots are free. An image already in the cache is not encoded again, even for another request.",
	},
	{
		id: "kvm",
		label: "KVCacheManager",
		sub: "block hash + image hash",
		col: 2,
		row: 2,
		group: 2,
		note: "Every placeholder token has the same id, so a block's hash also includes the hash of each image it overlaps. Two prompts with different images never share KV blocks.",
	},
	{
		id: "venc",
		label: "Vision encoder",
		sub: "embed_multimodal()",
		col: 3,
		row: 0,
		group: 3,
		note: "<code>EncoderRunner.execute_mm_encoder()</code> batches the scheduled images by modality and runs the model's vision tower; for Qwen2-VL a 32-layer ViT whose output is merged 2×2 and projected to the language model's width, 3,584.",
	},
	{
		id: "ecache",
		label: "Encoder cache",
		sub: "embeddings on GPU",
		col: 3,
		row: 1,
		group: 3,
		note: "The encoder's output tensor, one row per placeholder token, stored by image hash until no running request needs it.",
	},
	{
		id: "merge",
		label: "Embedding merge",
		sub: "embed_input_ids()",
		col: 3,
		row: 2,
		group: 3,
		note: "For each step, <code>gather_mm_embeddings()</code> picks the rows that fall in the step's tokens, and <code>embed_input_ids()</code> writes them over the placeholder tokens' text embeddings before the first decoder layer.",
	},
];

export const vllmMmEdges: BoxEdge[] = [
	{ from: "req", to: "fetch" },
	{ from: "fetch", to: "proc" },
	{ from: "proc", to: "upd" },
	{ from: "upd", to: "sched" },
	{ from: "sched", to: "ecm", both: true },
	{ from: "sched", to: "kvm", both: true },
	{ from: "sched", to: "venc", label: "encoder inputs" },
	{ from: "venc", to: "ecache" },
	{ from: "ecache", to: "merge" },
];

export const vllmPdParticipants: Participant[] = [
	{ id: "client", label: "Client" },
	{ id: "proxy", label: "Proxy" },
	{ id: "p", label: "Prefill vLLM", sub: "NixlConnector" },
	{ id: "d", label: "Decode vLLM", sub: "NixlConnector" },
];

export const vllmPdFlow: Message[] = [
	{
		from: "client",
		to: "proxy",
		label: "completion request",
		step: "request",
		note: "The client talks to a proxy, which hides that two vLLM instances serve each request.",
	},
	{
		from: "proxy",
		to: "p",
		label: "max_tokens=1, do_remote_decode",
		step: "to P",
		phase: "Prefill instance",
		note: "The proxy sends the request to the prefill instance with <code>max_tokens = 1</code> and <code>kv_transfer_params = {do_remote_decode: true}</code>.",
	},
	{
		from: "p",
		to: "p",
		label: "prefill, keep blocks",
		step: "prefill",
		note: "P runs an ordinary prefill. When the request finishes, the connector's <code>request_finished()</code> tells the scheduler not to free its blocks yet, and returns <code>remote_block_ids</code>, <code>remote_engine_id</code>, host and port. The blocks are leased for a timeout in case D never reads them.",
	},
	{
		from: "p",
		to: "proxy",
		label: "response + kv_transfer_params",
		step: "params",
		reply: true,
		note: "The response carries the transfer parameters.",
	},
	{
		from: "proxy",
		to: "d",
		label: "request + do_remote_prefill",
		step: "to D",
		phase: "Decode instance",
		note: "The proxy forwards the original request to D with P's transfer parameters and <code>do_remote_prefill: true</code>.",
	},
	{
		from: "d",
		to: "d",
		label: "allocate",
		step: "allocate",
		note: "D's scheduler asks the connector how many tokens are available remotely (<code>get_num_new_matched_tokens()</code> returns the prompt length and <code>async = True</code>), allocates local blocks for them and parks the request in <code>WAITING_FOR_REMOTE_KVS</code>. Other requests keep decoding meanwhile.",
	},
	{
		from: "d",
		to: "p",
		label: "NIXL READ remote blocks",
		step: "read",
		tone: 3,
		note: "D's worker posts one-sided RDMA READs from P's registered KV memory into its own blocks (after a one-time handshake that exchanges NIXL agent metadata). P's GPU is not involved.",
	},
	{
		from: "d",
		to: "p",
		label: "notify: done reading",
		step: "notify",
		note: "When the reads complete, D sends a NIXL notification and P frees the leased blocks.",
	},
	{
		from: "d",
		to: "d",
		label: "decode",
		step: "decode",
		note: "The request moves back to the waiting queue with all prompt KV in place. <code>_update_waiting_for_remote_kv()</code> sets <code>num_computed_tokens = prompt_len - 1</code>, so D computes the last prompt token to get the logits for the first output token, then decodes as usual.",
	},
	{
		from: "d",
		to: "client",
		label: "token stream",
		step: "stream",
		reply: true,
		tone: 1,
		note: "D streams the tokens back through the proxy.",
	},
];

// ---------------------------------------------------------------- SGLang

export const sglangNodes: BoxNode[] = [
	{ id: "main", label: "main process", col: 1, row: 0, h: 2, group: -1 },
	{
		id: "sp",
		label: "Scheduler process (one per TP rank)",
		col: 2,
		row: 0,
		w: 2,
		h: 3,
		group: -1,
	},
	{
		id: "client",
		label: "Client",
		sub: "HTTP / OpenAI API",
		col: 0,
		row: 1,
		group: 0,
		note: "Calls the native <code>/generate</code> endpoint or the OpenAI-compatible ones.",
	},
	{
		id: "http",
		label: "HTTP server",
		sub: "FastAPI",
		col: 1,
		row: 0,
		group: 1,
		note: "Runs in the main process, next to the TokenizerManager (sglang/srt/entrypoints/http_server.py).",
	},
	{
		id: "tm",
		label: "TokenizerManager",
		sub: "tokenize, track state",
		col: 1,
		row: 1,
		group: 1,
		note: "<code>generate_request()</code> tokenizes the prompt, keeps a <code>ReqState</code> per request id and sends a <code>TokenizedGenerateReqInput</code> to the scheduler over a ZMQ PUSH socket. Its <code>handle_loop</code> receives detokenized text and wakes the waiting HTTP handler.",
	},
	{
		id: "detok",
		label: "DetokenizerManager",
		sub: "own process",
		col: 1,
		row: 2,
		group: 4,
		note: "A separate process that turns token ids into text incrementally and sends <code>BatchStrOutput</code> back to the TokenizerManager.",
	},
	{
		id: "sched",
		label: "Scheduler",
		sub: "event loop",
		col: 2,
		row: 1,
		group: 2,
		note: "One process per tensor-parallel rank, each running the same loop: receive requests, pick the next batch, run it, process the result. Rank 0 receives from the TokenizerManager and broadcasts to the others.",
	},
	{
		id: "tree",
		label: "RadixCache",
		sub: "prefix tree",
		col: 2,
		row: 0,
		group: 2,
		note: "Maps token sequences to the KV slots that hold them, shares prefixes between requests and evicts least recently used leaves.",
	},
	{
		id: "worker",
		label: "TpModelWorker",
		sub: "ModelRunner",
		col: 3,
		row: 1,
		group: 3,
		note: "Runs in the scheduler process: no inter-process hop between scheduling and the forward pass. The ModelRunner builds a <code>ForwardBatch</code>, picks a CUDA graph, runs the model and samples.",
	},
	{
		id: "pools",
		label: "memory pools",
		sub: "req_to_token, KV slots",
		col: 3,
		row: 0,
		group: 3,
		note: "<code>ReqToTokenPool</code> (one row of slot ids per running request), the slot allocator, and the per-layer K and V buffers on the GPU.",
	},
];

export const sglangEdges: BoxEdge[] = [
	{ from: "client", to: "http", label: "HTTP" },
	{ from: "http", to: "tm" },
	{ from: "tm", to: "sched", label: "ZMQ" },
	{ from: "sched", to: "tree", both: true },
	{ from: "sched", to: "worker", both: true },
	{ from: "worker", to: "pools", both: true },
	{ from: "tree", to: "pools", dashed: true },
	{ from: "sched", to: "detok", label: "ZMQ" },
	{ from: "detok", to: "tm", label: "ZMQ" },
];

export const sglangParticipants: Participant[] = [
	{ id: "client", label: "Client" },
	{ id: "tm", label: "Tokenizer", sub: "Manager" },
	{ id: "sched", label: "Scheduler", sub: "+ RadixCache" },
	{ id: "runner", label: "ModelRunner", sub: "same process" },
	{ id: "detok", label: "Detokenizer", sub: "Manager" },
];

export const sglangLifecycle: Message[] = [
	{
		from: "client",
		to: "tm",
		label: "POST /generate",
		step: "HTTP",
		phase: "Front end",
		note: "The HTTP handler calls <code>TokenizerManager.generate_request()</code> and waits on the request's state.",
	},
	{
		from: "tm",
		to: "tm",
		label: "tokenize, ReqState",
		step: "tokenize",
		note: "The prompt is tokenized (multimodal inputs are processed here too) into a <code>TokenizedGenerateReqInput</code>.",
	},
	{
		from: "tm",
		to: "sched",
		label: "TokenizedGenerateReqInput (ZMQ)",
		step: "send",
		note: "Sent over a ZMQ PUSH socket. The scheduler's <code>recv_requests()</code> polls it at the top of every loop iteration and <code>handle_generate_request()</code> wraps it in a <code>Req</code> on the waiting queue.",
	},
	{
		from: "sched",
		to: "sched",
		label: "match prefix, allocate slots",
		step: "schedule",
		phase: "Scheduler loop",
		note: "<code>get_new_batch_prefill()</code> orders the waiting queue by the schedule policy, matches each prompt in the radix tree, and a <code>PrefillAdder</code> admits requests while the token budget and memory last. Admitted requests get a <code>req_to_token</code> row and KV slots for their new tokens (<code>out_cache_loc</code>).",
	},
	{
		from: "sched",
		to: "runner",
		label: "ForwardBatch",
		step: "run",
		note: "<code>run_batch()</code> turns the <code>ScheduleBatch</code> (mostly CPU data) into a <code>ForwardBatch</code> (GPU tensors) and calls the model worker directly: same process, no serialisation.",
	},
	{
		from: "runner",
		to: "runner",
		label: "store KV, attention, sample",
		step: "forward",
		note: "Each attention layer writes its new K and V at <code>out_cache_loc</code> and attends over the slots in the request's <code>req_to_token</code> row. The batch replays a CUDA graph when it is a decode batch of a captured size.",
	},
	{
		from: "runner",
		to: "sched",
		label: "next token ids",
		step: "result",
		reply: true,
		note: "With the overlap scheduler, the CPU has already scheduled the next batch while this one ran; it now processes this result.",
	},
	{
		from: "sched",
		to: "sched",
		label: "process_batch_result()",
		step: "update",
		note: "Appends the tokens, checks stop conditions, and for finished requests inserts their KV into the radix tree and releases their row.",
	},
	{
		from: "sched",
		to: "detok",
		label: "BatchTokenIDOutput (ZMQ)",
		step: "ids",
		phase: "Back to the client",
		note: "New token ids for every request in the batch go to the DetokenizerManager in one message.",
	},
	{
		from: "detok",
		to: "tm",
		label: "BatchStrOutput (ZMQ)",
		step: "text",
		reply: true,
		note: "Incrementally decoded text goes back to the TokenizerManager.",
	},
	{
		from: "tm",
		to: "client",
		label: "SSE chunk",
		step: "stream",
		reply: true,
		tone: 1,
		note: "The TokenizerManager's <code>handle_loop</code> sets the request's event and the HTTP handler streams the chunk.",
	},
];

export const sglangPdParticipants: Participant[] = [
	{ id: "client", label: "Client" },
	{ id: "router", label: "Router", sub: "PD mode" },
	{ id: "p", label: "Prefill server", sub: "KVSender" },
	{ id: "d", label: "Decode server", sub: "KVReceiver" },
];

export const sglangPdFlow: Message[] = [
	{
		from: "client",
		to: "router",
		label: "generate request",
		step: "request",
		note: "The client calls the router (sgl-model-gateway in PD mode).",
	},
	{
		from: "router",
		to: "p",
		label: "request + bootstrap_room",
		step: "to P",
		phase: "Dual dispatch",
		note: "The router picks a prefill and a decode server and sends the same request to both at once, tagged with the prefill server's <code>bootstrap_host</code> and a random <code>bootstrap_room</code> that identifies this transfer.",
	},
	{
		from: "router",
		to: "d",
		label: "request + bootstrap_room",
		step: "to D",
		note: "The decode server gets the same request and bootstrap information.",
	},
	{
		from: "d",
		to: "d",
		label: "prealloc",
		step: "prealloc",
		phase: "Handshake",
		note: "D creates a KV receiver, handshakes with P's bootstrap server, and as soon as it has memory reserves a <code>req_to_token</code> row and KV slots for the whole prompt.",
	},
	{
		from: "d",
		to: "p",
		label: "destination KV page indices",
		step: "metadata",
		note: "<code>send_metadata()</code> tells P where to write: D's page indices for this request and a metadata buffer slot.",
	},
	{
		from: "p",
		to: "p",
		label: "bootstrap → waiting → prefill",
		step: "prefill",
		phase: "Transfer",
		note: "On P the request waits in the bootstrap queue until the handshake is done, then is scheduled like any prefill, chunk by chunk.",
	},
	{
		from: "p",
		to: "d",
		label: "RDMA WRITE KV pages",
		step: "write",
		tone: 3,
		note: "After each chunk, <code>send_kv_chunk()</code> hands the chunk's page indices to the sender. The Mooncake backend groups runs of consecutive pages and writes them per layer straight into D's GPU memory with <code>batch_transfer_sync_write</code>. The last chunk also writes the first output token and logprobs into D's metadata buffer.",
	},
	{
		from: "p",
		to: "d",
		label: "status: Success",
		step: "done",
		note: "P marks the transfer complete; its inflight queue releases the request's KV.",
	},
	{
		from: "d",
		to: "d",
		label: "decode",
		step: "decode",
		phase: "Decode",
		note: "D's transfer queue sees <code>KVPoll.Success</code>. The request joins a <code>PrebuiltExtendBatch</code>, which fills in metadata without running a prefill forward, and merges into the running decode batch.",
	},
	{
		from: "d",
		to: "client",
		label: "token stream",
		step: "stream",
		reply: true,
		tone: 1,
		note: "The router streams D's output back to the client.",
	},
];
