// Generated by a scratch script from the Qwen2-VL-7B-Instruct tokenizer (transformers 5.18.0,
// tokenizers 0.23.2). Figure data for the tokenization and multimodal sections of vllm-internals.mdx.
import type { TokenView } from "./tokenStrip";

export const chatTemplateViews: TokenView[] = [
	{
		label: "Rendered prompt",
		tokens: [
			{
				text: "<|im_start|>",
				id: 151644,
				kind: "special",
				note: "<code>&lt;|im_start|&gt;</code> opens a message; the role name follows.",
			},
			{
				text: "system",
				id: 8948,
				kind: "role",
				note: "The system message was added by the chat template: the request had none.",
			},
			{
				text: "↵",
				id: 198,
				kind: "space",
			},
			{
				text: "You",
				id: 2610,
				kind: "text",
			},
			{
				text: "␣are",
				id: 525,
				kind: "text",
			},
			{
				text: "␣a",
				id: 264,
				kind: "text",
			},
			{
				text: "␣helpful",
				id: 10950,
				kind: "text",
			},
			{
				text: "␣assistant",
				id: 17847,
				kind: "text",
			},
			{
				text: ".",
				id: 13,
				kind: "text",
			},
			{
				text: "<|im_end|>",
				id: 151645,
				kind: "special",
				note: "<code>&lt;|im_end|&gt;</code> closes a message.",
			},
			{
				text: "↵",
				id: 198,
				kind: "space",
			},
			{
				text: "<|im_start|>",
				id: 151644,
				kind: "special",
				note: "<code>&lt;|im_start|&gt;</code> opens a message; the role name follows.",
			},
			{
				text: "user",
				id: 872,
				kind: "role",
			},
			{
				text: "↵",
				id: 198,
				kind: "space",
			},
			{
				text: "<|vision_start|>",
				id: 151652,
				kind: "vision",
				note: "Marks where an image starts.",
			},
			{
				text: "<|image_pad|>",
				id: 151655,
				kind: "image",
				note: "One placeholder token per image, until the multimodal processor expands it.",
			},
			{
				text: "<|vision_end|>",
				id: 151653,
				kind: "vision",
				note: "Marks where an image ends.",
			},
			{
				text: "What",
				id: 3838,
				kind: "text",
			},
			{
				text: "␣is",
				id: 374,
				kind: "text",
			},
			{
				text: "␣in",
				id: 304,
				kind: "text",
			},
			{
				text: "␣this",
				id: 419,
				kind: "text",
			},
			{
				text: "␣image",
				id: 2168,
				kind: "text",
			},
			{
				text: "?",
				id: 30,
				kind: "text",
			},
			{
				text: "<|im_end|>",
				id: 151645,
				kind: "special",
				note: "<code>&lt;|im_end|&gt;</code> closes a message.",
			},
			{
				text: "↵",
				id: 198,
				kind: "space",
			},
			{
				text: "<|im_start|>",
				id: 151644,
				kind: "special",
				note: "<code>&lt;|im_start|&gt;</code> opens a message; the role name follows.",
			},
			{
				text: "assistant",
				id: 77091,
				kind: "role",
			},
			{
				text: "↵",
				id: 198,
				kind: "space",
			},
		],
	},
];

export const imageExpansionViews: TokenView[] = [
	{
		label: "Before the processor",
		tokens: [
			{
				text: "<|im_start|>",
				id: 151644,
				kind: "special",
				note: "<code>&lt;|im_start|&gt;</code> opens a message; the role name follows.",
			},
			{
				text: "system",
				id: 8948,
				kind: "role",
				note: "The system message was added by the chat template: the request had none.",
			},
			{
				text: "↵",
				id: 198,
				kind: "space",
			},
			{
				text: "You",
				id: 2610,
				kind: "text",
			},
			{
				text: "␣are",
				id: 525,
				kind: "text",
			},
			{
				text: "␣a",
				id: 264,
				kind: "text",
			},
			{
				text: "␣helpful",
				id: 10950,
				kind: "text",
			},
			{
				text: "␣assistant",
				id: 17847,
				kind: "text",
			},
			{
				text: ".",
				id: 13,
				kind: "text",
			},
			{
				text: "<|im_end|>",
				id: 151645,
				kind: "special",
				note: "<code>&lt;|im_end|&gt;</code> closes a message.",
			},
			{
				text: "↵",
				id: 198,
				kind: "space",
			},
			{
				text: "<|im_start|>",
				id: 151644,
				kind: "special",
				note: "<code>&lt;|im_start|&gt;</code> opens a message; the role name follows.",
			},
			{
				text: "user",
				id: 872,
				kind: "role",
			},
			{
				text: "↵",
				id: 198,
				kind: "space",
			},
			{
				text: "<|vision_start|>",
				id: 151652,
				kind: "vision",
				note: "Marks where an image starts.",
			},
			{
				text: "<|image_pad|>",
				id: 151655,
				kind: "image",
				note: "One placeholder token per image, until the multimodal processor expands it.",
			},
			{
				text: "<|vision_end|>",
				id: 151653,
				kind: "vision",
				note: "Marks where an image ends.",
			},
			{
				text: "What",
				id: 3838,
				kind: "text",
			},
			{
				text: "␣is",
				id: 374,
				kind: "text",
			},
			{
				text: "␣in",
				id: 304,
				kind: "text",
			},
			{
				text: "␣this",
				id: 419,
				kind: "text",
			},
			{
				text: "␣image",
				id: 2168,
				kind: "text",
			},
			{
				text: "?",
				id: 30,
				kind: "text",
			},
			{
				text: "<|im_end|>",
				id: 151645,
				kind: "special",
				note: "<code>&lt;|im_end|&gt;</code> closes a message.",
			},
			{
				text: "↵",
				id: 198,
				kind: "space",
			},
			{
				text: "<|im_start|>",
				id: 151644,
				kind: "special",
				note: "<code>&lt;|im_start|&gt;</code> opens a message; the role name follows.",
			},
			{
				text: "assistant",
				id: 77091,
				kind: "role",
			},
			{
				text: "↵",
				id: 198,
				kind: "space",
			},
		],
	},
	{
		label: "After the processor",
		tokens: [
			{
				text: "<|im_start|>",
				id: 151644,
				kind: "special",
				note: "<code>&lt;|im_start|&gt;</code> opens a message; the role name follows.",
			},
			{
				text: "system",
				id: 8948,
				kind: "role",
				note: "The system message was added by the chat template: the request had none.",
			},
			{
				text: "↵",
				id: 198,
				kind: "space",
			},
			{
				text: "You",
				id: 2610,
				kind: "text",
			},
			{
				text: "␣are",
				id: 525,
				kind: "text",
			},
			{
				text: "␣a",
				id: 264,
				kind: "text",
			},
			{
				text: "␣helpful",
				id: 10950,
				kind: "text",
			},
			{
				text: "␣assistant",
				id: 17847,
				kind: "text",
			},
			{
				text: ".",
				id: 13,
				kind: "text",
			},
			{
				text: "<|im_end|>",
				id: 151645,
				kind: "special",
				note: "<code>&lt;|im_end|&gt;</code> closes a message.",
			},
			{
				text: "↵",
				id: 198,
				kind: "space",
			},
			{
				text: "<|im_start|>",
				id: 151644,
				kind: "special",
				note: "<code>&lt;|im_start|&gt;</code> opens a message; the role name follows.",
			},
			{
				text: "user",
				id: 872,
				kind: "role",
			},
			{
				text: "↵",
				id: 198,
				kind: "space",
			},
			{
				text: "<|vision_start|>",
				id: 151652,
				kind: "vision",
				note: "Marks where an image starts.",
			},
			{
				text: "<|image_pad|>",
				id: 151655,
				kind: "image",
				note: "1196 copies of <code>&lt;|image_pad|&gt;</code>: one per vision-encoder output embedding. Their embeddings are overwritten with the image's before the first layer.",
				count: 1196,
			},
			{
				text: "<|vision_end|>",
				id: 151653,
				kind: "vision",
				note: "Marks where an image ends.",
			},
			{
				text: "What",
				id: 3838,
				kind: "text",
			},
			{
				text: "␣is",
				id: 374,
				kind: "text",
			},
			{
				text: "␣in",
				id: 304,
				kind: "text",
			},
			{
				text: "␣this",
				id: 419,
				kind: "text",
			},
			{
				text: "␣image",
				id: 2168,
				kind: "text",
			},
			{
				text: "?",
				id: 30,
				kind: "text",
			},
			{
				text: "<|im_end|>",
				id: 151645,
				kind: "special",
				note: "<code>&lt;|im_end|&gt;</code> closes a message.",
			},
			{
				text: "↵",
				id: 198,
				kind: "space",
			},
			{
				text: "<|im_start|>",
				id: 151644,
				kind: "special",
				note: "<code>&lt;|im_start|&gt;</code> opens a message; the role name follows.",
			},
			{
				text: "assistant",
				id: 77091,
				kind: "role",
			},
			{
				text: "↵",
				id: 198,
				kind: "space",
			},
		],
	},
];
