// Figure data for the AOTAutograd post (src/content/posts/aot-autograd.mdx).
// Generated from torch 2.13.0 (git cf30153c) by a script that wraps networkx.minimum_cut and
// torch._functorch.partitioners.solve_min_cut while torch.compile runs the backward, then contracts
// the flow network to FX nodes: each node's (X_in, X_out) pair becomes one box, backward-only nodes
// that must run in the backward are merged into the sink, and nodes on no source-sink path are
// dropped. Capacities are the partitioner's own numbers. Do not edit by hand.
import type { FlowEdge, FlowNode } from "./minCut";

// sin3(x) = x.sin().sin().sin() with x: f32[4, 16].
export const sinChainNodes: FlowNode[] = [
	{
		id: "primals_1",
		label: "primals_1",
		op: "input",
		cap: 281,
		kind: "input",
		note: "primals_1: f32[4, 16], capacity 256 B × 1.1^1 = 281. Banned from recomputation (primal input), so the source feeds it directly.",
	},
	{
		id: "sin",
		label: "sin",
		op: "sin",
		cap: 562,
		kind: "fwd",
		note: "sin: f32[4, 16], capacity 256 B × 1.1^1 × 2 (every user can fuse with it) = 562.",
	},
	{
		id: "cos_2",
		label: "cos_2",
		op: "cos",
		cap: 562,
		kind: "bwd",
		note: "cos_2: f32[4, 16], capacity 256 B × 1.1^1 × 2 (every user can fuse with it) = 562. A backward op that does not need the incoming gradient, so the forward could compute and save it instead.",
	},
	{
		id: "sin_1",
		label: "sin_1",
		op: "sin",
		cap: 562,
		kind: "fwd",
		note: "sin_1: f32[4, 16], capacity 256 B × 1.1^1 × 2 (every user can fuse with it) = 562.",
	},
	{
		id: "cos_1",
		label: "cos_1",
		op: "cos",
		cap: 562,
		kind: "bwd",
		note: "cos_1: f32[4, 16], capacity 256 B × 1.1^1 × 2 (every user can fuse with it) = 562. A backward op that does not need the incoming gradient, so the forward could compute and save it instead.",
	},
	{
		id: "cos",
		label: "cos",
		op: "cos",
		cap: 562,
		kind: "bwd",
		note: "cos: f32[4, 16], capacity 256 B × 1.1^1 × 2 (every user can fuse with it) = 562. A backward op that does not need the incoming gradient, so the forward could compute and save it instead.",
	},
];
export const sinChainEdges: FlowEdge[] = [
	{ from: "source", to: "primals_1", note: "primal input" },
	{ from: "primals_1", to: "sin", note: "data dependency" },
	{ from: "primals_1", to: "cos_2", note: "data dependency" },
	{ from: "sin", to: "sin_1", note: "data dependency" },
	{ from: "sin", to: "cos_1", note: "data dependency" },
	{ from: "sin_1", to: "cos", note: "data dependency" },
	{ from: "cos", to: "sink", note: "needed by the backward" },
	{ from: "cos_1", to: "sink", note: "needed by the backward" },
	{ from: "cos_2", to: "sink", note: "needed by the backward" },
];
/** What networkx returned when the partitioner ran: cut value and saved nodes. */
export const sinChainExpected = { value: 281, saved: ["primals_1"] };

// rms_silu(x, g, w): RMSNorm, then a linear layer, then SiLU, with x: f32[4, 16], g: f32[16], w: f32[16, 8].
export const rmsSiluNodes: FlowNode[] = [
	{
		id: "primals_1",
		label: "primals_1",
		op: "input",
		cap: 281,
		kind: "input",
		note: "primals_1: f32[4, 16], capacity 256 B × 1.1^1 = 281. Banned from recomputation (primal input), so the source feeds it directly.",
	},
	{
		id: "pow_1",
		label: "pow_1",
		op: "pow",
		cap: 748,
		kind: "fwd",
		note: "pow_1: f32[4, 16], capacity 256 B × 1.1^4 × 2 (every user can fuse with it) = 748.",
	},
	{
		id: "mul",
		label: "mul",
		op: "mul",
		cap: 562,
		kind: "fwd",
		note: "mul: f32[4, 16], capacity 256 B × 1.1^1 × 2 (every user can fuse with it) = 562.",
	},
	{
		id: "pow_3",
		label: "pow_3",
		op: "pow",
		cap: 562,
		kind: "bwd",
		note: "pow_3: f32[4, 16], capacity 256 B × 1.1^1 × 2 (every user can fuse with it) = 562. A backward op that does not need the incoming gradient, so the forward could compute and save it instead.",
	},
	{
		id: "primals_2",
		label: "primals_2",
		op: "input",
		cap: 70,
		kind: "input",
		note: "primals_2: f32[16], capacity 64 B × 1.1^1 = 70. Banned from recomputation (primal input), so the source feeds it directly.",
	},
	{
		id: "mul_1",
		label: "mul_1",
		op: "mul",
		cap: 281,
		kind: "fwd",
		note: "mul_1: f32[4, 16], capacity 256 B × 1.1^1 = 281. Banned from recomputation (materialized in backward), so the source feeds it directly.",
	},
	{
		id: "primals_3",
		label: "primals_3",
		op: "input",
		cap: 563,
		kind: "input",
		note: "primals_3: f32[16, 8], capacity 512 B × 1.1^1 = 563. Banned from recomputation (primal input), so the source feeds it directly.",
	},
	{
		id: "mm",
		label: "mm",
		op: "mm",
		cap: 140,
		kind: "fwd",
		note: "mm: f32[4, 8], capacity 128 B × 1.1^1 = 140. Banned from recomputation (not in recomputable allowlist), so the source feeds it directly.",
	},
	{
		id: "permute_1",
		label: "permute_1",
		op: "permute",
		cap: 563,
		kind: "bwd",
		note: "permute_1: f32[8, 16], capacity 512 B × 1.1^1 = 563. A backward op that does not need the incoming gradient, so the forward could compute and save it instead.",
	},
	{
		id: "mean",
		label: "mean",
		op: "mean",
		cap: 42,
		kind: "fwd",
		note: "mean: f32[4, 1], capacity 16 B × 1.1^3 × 2 (every user can fuse with it) = 42. Banned from recomputation (reduction op), so the source feeds it directly.",
	},
	{
		id: "add",
		label: "add",
		op: "add",
		cap: 38,
		kind: "fwd",
		note: "add: f32[4, 1], capacity 16 B × 1.1^2 × 2 (every user can fuse with it) = 38.",
	},
	{
		id: "rsqrt",
		label: "rsqrt",
		op: "rsqrt",
		cap: 34,
		kind: "fwd",
		note: "rsqrt: f32[4, 1], capacity 16 B × 1.1^1 × 2 (every user can fuse with it) = 34.",
	},
	{
		id: "pow_2",
		label: "pow_2",
		op: "pow",
		cap: 34,
		kind: "bwd",
		note: "pow_2: f32[4, 1], capacity 16 B × 1.1^1 × 2 (every user can fuse with it) = 34. A backward op that does not need the incoming gradient, so the forward could compute and save it instead.",
	},
	{
		id: "permute",
		label: "permute",
		op: "permute",
		cap: 281,
		kind: "bwd",
		note: "permute: f32[16, 4], capacity 256 B × 1.1^1 = 281. A backward op that does not need the incoming gradient, so the forward could compute and save it instead.",
	},
	{
		id: "sigmoid",
		label: "sigmoid",
		op: "sigmoid",
		cap: 280,
		kind: "bwd",
		note: "sigmoid: f32[4, 8], capacity 128 B × 1.1^1 × 2 (every user can fuse with it) = 280. A backward op that does not need the incoming gradient, so the forward could compute and save it instead.",
	},
	{
		id: "mul_3",
		label: "mul_3",
		op: "mul",
		cap: 280,
		kind: "bwd",
		note: "mul_3: f32[4, 8], capacity 128 B × 1.1^1 × 2 (every user can fuse with it) = 280. A backward op that does not need the incoming gradient, so the forward could compute and save it instead.",
	},
	{
		id: "sub",
		label: "sub",
		op: "sub",
		cap: 280,
		kind: "bwd",
		note: "sub: f32[4, 8], capacity 128 B × 1.1^1 × 2 (every user can fuse with it) = 280. A backward op that does not need the incoming gradient, so the forward could compute and save it instead.",
	},
	{
		id: "add_2",
		label: "add_2",
		op: "add",
		cap: 280,
		kind: "bwd",
		note: "add_2: f32[4, 8], capacity 128 B × 1.1^1 × 2 (every user can fuse with it) = 280. A backward op that does not need the incoming gradient, so the forward could compute and save it instead.",
	},
	{
		id: "mul_11",
		label: "mul_11",
		op: "mul",
		cap: 562,
		kind: "bwd",
		note: "mul_11: f32[4, 16], capacity 256 B × 1.1^1 × 2 (every user can fuse with it) = 562. A backward op that does not need the incoming gradient, so the forward could compute and save it instead.",
	},
];
export const rmsSiluEdges: FlowEdge[] = [
	{ from: "source", to: "primals_1", note: "primal input" },
	{ from: "source", to: "primals_2", note: "primal input" },
	{ from: "source", to: "primals_3", note: "primal input" },
	{ from: "source", to: "mean", note: "reduction op" },
	{ from: "source", to: "mul_1", note: "materialized in backward" },
	{ from: "source", to: "mm", note: "not in recomputable allowlist" },
	{ from: "primals_1", to: "pow_1", note: "data dependency" },
	{ from: "primals_1", to: "mul", note: "data dependency" },
	{ from: "primals_1", to: "sink", note: "needed by the backward" },
	{ from: "primals_1", to: "pow_3", note: "data dependency" },
	{ from: "primals_2", to: "mul_1", note: "data dependency" },
	{ from: "primals_2", to: "sink", note: "needed by the backward" },
	{ from: "primals_3", to: "mm", note: "data dependency" },
	{ from: "primals_3", to: "permute_1", note: "data dependency" },
	{ from: "pow_1", to: "mean", note: "data dependency" },
	{ from: "mean", to: "add", note: "data dependency" },
	{ from: "add", to: "rsqrt", note: "data dependency" },
	{ from: "rsqrt", to: "mul", note: "data dependency" },
	{ from: "rsqrt", to: "sink", note: "needed by the backward" },
	{ from: "rsqrt", to: "pow_2", note: "data dependency" },
	{ from: "mul", to: "mul_1", note: "data dependency" },
	{ from: "mul", to: "sink", note: "needed by the backward" },
	{ from: "mul_1", to: "mm", note: "data dependency" },
	{ from: "mul_1", to: "permute", note: "data dependency" },
	{ from: "mm", to: "sigmoid", note: "data dependency" },
	{ from: "mm", to: "mul_3", note: "data dependency" },
	{ from: "sigmoid", to: "sink", note: "needed by the backward" },
	{ from: "sigmoid", to: "sub", note: "data dependency" },
	{ from: "sub", to: "mul_3", note: "data dependency" },
	{ from: "mul_3", to: "add_2", note: "data dependency" },
	{ from: "add_2", to: "sink", note: "needed by the backward" },
	{ from: "permute", to: "sink", note: "needed by the backward" },
	{ from: "permute_1", to: "sink", note: "needed by the backward" },
	{ from: "pow_2", to: "sink", note: "needed by the backward" },
	{ from: "pow_3", to: "mul_11", note: "data dependency" },
	{ from: "mul_11", to: "sink", note: "needed by the backward" },
];
/** What networkx returned when the partitioner ran: cut value and saved nodes. */
export const rmsSiluExpected = {
	value: 1369,
	saved: ["mm", "permute", "permute_1", "primals_1", "primals_2", "rsqrt"],
};
