// Figure data for the Torch FX post (src/content/posts/torch-fx-graph.mdx).
// Generated by a script that ran every example on torch 2.13.0 (git cf30153c); do not edit by hand.
import type { GraphEdge, GraphNode } from "../graph/dependencyGraph";
import type { CodeStage, StageTag } from "./llvmData";
import type { SymbolicShapesData } from "./symbolicShapes";

export const traceStages: CodeStage[] = [
	{
		id: "src",
		label: "source",
		tool: "the module being traced",
		lang: "python",
		code: "class Block(nn.Module):\n    def __init__(self):\n        super().__init__()\n        self.linear = nn.Linear(4, 4)\n        self.scale = nn.Parameter(torch.ones(4))\n\n    def forward(self, x):\n        y = self.linear(x)\n        y = torch.relu(y)\n        y = y * self.scale\n        return y.sum(dim=-1)",
		marks: [
			[6, "x"],
			[7, "linear"],
			[8, "relu"],
			[9, "mul"],
			[10, "sum"],
		],
		note: "symbolic_trace(Block()) calls forward once, with a Proxy in place of x. Every operation on a Proxy adds one node to the graph. Step through to watch it grow.",
	},
	{
		id: "x",
		label: "x",
		tool: "print(tracer.graph) after the node is created",
		lang: "text",
		code: "graph():\n    %x : [num_users=0] = placeholder[target=x]",
		marks: [[1, "x"]],
		note: "Tracing starts by calling forward with a Proxy for x. Creating that Proxy adds a placeholder node.",
	},
	{
		id: "linear",
		label: "linear",
		tool: "print(tracer.graph) after the node is created",
		lang: "text",
		code: "graph():\n    %x : [num_users=1] = placeholder[target=x]\n    %linear : [num_users=0] = call_module[target=linear](args = (%x,), kwargs = {})",
		marks: [
			[1, "x"],
			[2, "linear"],
		],
		note: "`self.linear(x)` goes through `nn.Module.__call__`, which the tracer patches. nn.Linear is a leaf module, so the tracer records one call_module node and does not trace inside it.",
	},
	{
		id: "relu",
		label: "relu",
		tool: "print(tracer.graph) after the node is created",
		lang: "text",
		code: "graph():\n    %x : [num_users=1] = placeholder[target=x]\n    %linear : [num_users=1] = call_module[target=linear](args = (%x,), kwargs = {})\n    %relu : [num_users=0] = call_function[target=torch.relu](args = (%linear,), kwargs = {})",
		marks: [
			[1, "x"],
			[2, "linear"],
			[3, "relu"],
		],
		note: "`torch.relu` sees a Proxy argument and dispatches through `__torch_function__` to the tracer, which records a call_function node. Note that x now has one user.",
	},
	{
		id: "scale",
		label: "scale",
		tool: "print(tracer.graph) after the node is created",
		lang: "text",
		code: "graph():\n    %x : [num_users=1] = placeholder[target=x]\n    %linear : [num_users=1] = call_module[target=linear](args = (%x,), kwargs = {})\n    %relu : [num_users=0] = call_function[target=torch.relu](args = (%linear,), kwargs = {})\n    %scale : [num_users=0] = get_attr[target=scale]",
		marks: [
			[1, "x"],
			[2, "linear"],
			[3, "relu"],
			[4, "mul"],
		],
		note: "Reading `self.scale` hits a patched parameter lookup: the tracer records a get_attr node with the parameter's qualified name.",
	},
	{
		id: "mul",
		label: "mul",
		tool: "print(tracer.graph) after the node is created",
		lang: "text",
		code: "graph():\n    %x : [num_users=1] = placeholder[target=x]\n    %linear : [num_users=1] = call_module[target=linear](args = (%x,), kwargs = {})\n    %relu : [num_users=1] = call_function[target=torch.relu](args = (%linear,), kwargs = {})\n    %scale : [num_users=1] = get_attr[target=scale]\n    %mul : [num_users=0] = call_function[target=operator.mul](args = (%relu, %scale), kwargs = {})",
		marks: [
			[1, "x"],
			[2, "linear"],
			[3, "relu"],
			[4, "mul"],
			[5, "mul"],
		],
		note: "`y * self.scale` calls `Proxy.__mul__`, which records `operator.mul`. Python operators become call_function nodes on the `operator` module.",
	},
	{
		id: "sum_1",
		label: "sum_1",
		tool: "print(tracer.graph) after the node is created",
		lang: "text",
		code: "graph():\n    %x : [num_users=1] = placeholder[target=x]\n    %linear : [num_users=1] = call_module[target=linear](args = (%x,), kwargs = {})\n    %relu : [num_users=1] = call_function[target=torch.relu](args = (%linear,), kwargs = {})\n    %scale : [num_users=1] = get_attr[target=scale]\n    %mul : [num_users=1] = call_function[target=operator.mul](args = (%relu, %scale), kwargs = {})\n    %sum_1 : [num_users=0] = call_method[target=sum](args = (%mul,), kwargs = {dim: -1})",
		marks: [
			[1, "x"],
			[2, "linear"],
			[3, "relu"],
			[4, "mul"],
			[5, "mul"],
			[6, "sum"],
		],
		note: '`y.sum(dim=-1)` is a method call on a Proxy, so it becomes a call_method node with target "sum". The name `sum_1` avoids shadowing the builtin `sum`.',
	},
	{
		id: "output",
		label: "output",
		tool: "print(tracer.graph) after the node is created",
		lang: "text",
		code: "graph():\n    %x : [num_users=1] = placeholder[target=x]\n    %linear : [num_users=1] = call_module[target=linear](args = (%x,), kwargs = {})\n    %relu : [num_users=1] = call_function[target=torch.relu](args = (%linear,), kwargs = {})\n    %scale : [num_users=1] = get_attr[target=scale]\n    %mul : [num_users=1] = call_function[target=operator.mul](args = (%relu, %scale), kwargs = {})\n    %sum_1 : [num_users=1] = call_method[target=sum](args = (%mul,), kwargs = {dim: -1})\n    return sum_1",
		marks: [
			[1, "x"],
			[2, "linear"],
			[3, "relu"],
			[4, "mul"],
			[5, "mul"],
			[6, "sum"],
			[7, "sum"],
		],
		note: "forward returned, so the tracer wraps the return value in an output node. The graph is complete.",
	},
];

export const traceTags: StageTag[] = [
	{
		tag: "x",
		label: "x",
	},
	{
		tag: "linear",
		label: "self.linear(x)",
	},
	{
		tag: "relu",
		label: "torch.relu(y)",
	},
	{
		tag: "mul",
		label: "y * self.scale",
	},
	{
		tag: "sum",
		label: "return y.sum(dim=-1)",
	},
];

export const blockNodes: GraphNode[] = [
	{
		id: "x",
		title: "x",
		subtitle: "placeholder · x",
		icon: {
			text: "in",
			bg: "#2f6fb0",
			fg: "#ffffff",
		},
		note: "op=placeholder, target=x, args=(), kwargs={}, users=[linear]. ShapeProp with x of shape (2, 4) stored tensor_meta f32[2, 4] in meta.",
	},
	{
		id: "linear",
		title: "linear",
		subtitle: "call_module · linear",
		icon: {
			text: "mod",
			bg: "#b8742a",
			fg: "#ffffff",
		},
		note: "op=call_module, target=linear, args=(%x,), kwargs={}, users=[relu]. ShapeProp with x of shape (2, 4) stored tensor_meta f32[2, 4] in meta.",
	},
	{
		id: "relu",
		title: "relu",
		subtitle: "call_function · torch.relu",
		icon: {
			text: "fn",
			bg: "#2f8a5b",
			fg: "#ffffff",
		},
		note: "op=call_function, target=torch.relu, args=(%linear,), kwargs={}, users=[mul]. ShapeProp with x of shape (2, 4) stored tensor_meta f32[2, 4] in meta.",
	},
	{
		id: "scale",
		title: "scale",
		subtitle: "get_attr · scale",
		icon: {
			text: "at",
			bg: "#7a62b8",
			fg: "#ffffff",
		},
		note: "op=get_attr, target=scale, args=(), kwargs={}, users=[mul]. ShapeProp with x of shape (2, 4) stored tensor_meta f32[4] in meta.",
	},
	{
		id: "mul",
		title: "mul",
		subtitle: "call_function · operator.mul",
		icon: {
			text: "fn",
			bg: "#2f8a5b",
			fg: "#ffffff",
		},
		note: "op=call_function, target=operator.mul, args=(%relu, %scale), kwargs={}, users=[sum_1]. ShapeProp with x of shape (2, 4) stored tensor_meta f32[2, 4] in meta.",
	},
	{
		id: "sum_1",
		title: "sum_1",
		subtitle: "call_method · sum",
		icon: {
			text: "me",
			bg: "#b33b5e",
			fg: "#ffffff",
		},
		note: "op=call_method, target=sum, args=(%mul,), kwargs={dim: -1}, users=[output]. ShapeProp with x of shape (2, 4) stored tensor_meta f32[2] in meta.",
	},
	{
		id: "output",
		title: "output",
		subtitle: "output · output",
		icon: {
			text: "out",
			bg: "#5f7380",
			fg: "#ffffff",
		},
		note: "op=output, target=output, args=(%sum_1,), kwargs={}, users=[]. ShapeProp with x of shape (2, 4) stored tensor_meta f32[2] in meta.",
	},
];

export const blockEdges: GraphEdge[] = [
	{
		from: "x",
		to: "linear",
	},
	{
		from: "linear",
		to: "relu",
	},
	{
		from: "relu",
		to: "mul",
	},
	{
		from: "scale",
		to: "mul",
	},
	{
		from: "mul",
		to: "sum_1",
	},
	{
		from: "sum_1",
		to: "output",
	},
];

export const editStages: CodeStage[] = [
	{
		id: "orig",
		label: "traced",
		tool: "gm = symbolic_trace(f); print(gm.code)",
		lang: "python",
		code: "def forward(self, x, y):\n    add = torch.add(x, y);  y = None\n    mul = torch.mul(add, 2);  add = None\n    sin = torch.sin(x);  x = sin = None\n    relu = torch.relu(mul);  mul = None\n    return relu\n",
		marks: [
			[1, "swap"],
			[3, "dce"],
		],
		note: "The traced function. The add and the unused sin are about to change. With x = [1, 2, 3] and y = [0.5, 2.5, -1] it returns [3.0, 9.0, 4.0].",
	},
	{
		id: "swap",
		label: "retarget",
		tool: "n.target = torch.sub; gm.recompile()",
		lang: "python",
		code: "def forward(self, x, y):\n    add = torch.sub(x, y);  y = None\n    mul = torch.mul(add, 2);  add = None\n    sin = torch.sin(x);  x = sin = None\n    relu = torch.relu(mul);  mul = None\n    return relu\n",
		marks: [
			[1, "swap"],
			[3, "dce"],
		],
		note: "Changing node.target swaps the function the node calls; the node keeps its name, add. Output: [1.0, 0.0, 8.0].",
	},
	{
		id: "dce",
		label: "dead code",
		tool: "gm.graph.eliminate_dead_code(); gm.recompile()",
		lang: "python",
		code: "def forward(self, x, y):\n    add = torch.sub(x, y);  x = y = None\n    mul = torch.mul(add, 2);  add = None\n    relu = torch.relu(mul);  mul = None\n    return relu\n",
		marks: [[1, "swap"]],
		note: "sin had no users and torch.sin has no side effects, so dead-code elimination removed it. x is now freed right after the sub.",
	},
	{
		id: "insert",
		label: "insert node",
		tool: "graph.inserting_after(mul) + replace_all_uses_with",
		lang: "python",
		code: "def forward(self, x, y):\n    add = torch.sub(x, y);  x = y = None\n    mul = torch.mul(add, 2);  add = None\n    clamp = torch.clamp(mul, max = 1.0);  mul = None\n    relu = torch.relu(clamp);  clamp = None\n    return relu\n",
		marks: [
			[1, "swap"],
			[3, "insert"],
			[4, "insert"],
		],
		note: "A new clamp node sits after mul and takes over mul's users. Output: [1.0, 0.0, 1.0].",
	},
];

export const editTags: StageTag[] = [
	{
		tag: "swap",
		label: "retargeted node",
	},
	{
		tag: "dce",
		label: "dead-code elimination",
	},
	{
		tag: "insert",
		label: "inserted node",
	},
];

export const tracerStages: CodeStage[] = [
	{
		id: "src",
		label: "source",
		tool: "the function",
		lang: "python",
		code: "def f(x, w):\n    y = x @ w\n    y = y.reshape(x.shape[0] * 2, -1)\n    return torch.relu(y) + x.shape[0]",
		marks: [
			[1, "mm"],
			[2, "reshape"],
			[3, "relu"],
		],
		note: "One function, captured five ways. Every capture is an FX graph; they differ in which operators appear and in how x.shape[0] is represented.",
	},
	{
		id: "st",
		label: "symbolic_trace",
		tool: "torch.fx.symbolic_trace(f).code",
		lang: "python",
		code: "def forward(self, x, w):\n    matmul = x @ w;  w = None\n    getattr_1 = x.shape\n    getitem = getattr_1[0];  getattr_1 = None\n    mul = getitem * 2;  getitem = None\n    reshape = matmul.reshape(mul, -1);  matmul = mul = None\n    relu = torch.relu(reshape);  reshape = None\n    getattr_2 = x.shape;  x = None\n    getitem_1 = getattr_2[0];  getattr_2 = None\n    add = relu + getitem_1;  relu = getitem_1 = None\n    return add\n",
		marks: [
			[1, "mm"],
			[2, "shape"],
			[3, "shape"],
			[4, "shape"],
			[5, "mm"],
			[6, "reshape"],
			[7, "shape"],
			[8, "shape"],
			[9, "relu"],
			[10, "add"],
		],
		note: "Proxy tracing. x.shape[0] becomes getattr and getitem nodes on a Proxy: the graph computes the size at run time, but nobody knows what the size is.",
	},
	{
		id: "dynamo",
		label: "Dynamo",
		tool: "torch.compile(f, backend=..., dynamic=True)",
		lang: "python",
		code: 'class GraphModule(torch.nn.Module):\n    def forward(self, s77: "Sym(s77)", s27: "Sym(s27)", L_x_: "f32[s77, s27]", s21: "Sym(s21)", L_w_: "f32[s27, s21]"):\n        l_x_ = L_x_\n        l_w_ = L_w_\n\n        # y = x @ w\n        y: "f32[s77, s21]" = l_x_ @ l_w_;  l_x_ = l_w_ = None\n\n        # y = y.reshape(x.shape[0] * 2, -1)\n        mul: "Sym(2*s77)" = s77 * 2\n        y_1: "f32[2*s77, (s21//2)]" = y.reshape(mul, -1);  y = mul = None\n\n        # return torch.relu(y) + x.shape[0]\n        relu: "f32[2*s77, (s21//2)]" = torch.relu(y_1);  y_1 = None\n        add: "f32[2*s77, (s21//2)]" = relu + s77;  relu = s77 = None\n        return (add,)',
		marks: [
			[5, "mm"],
			[6, "mm"],
			[8, "reshape"],
			[9, "shape"],
			[10, "reshape"],
			[12, "relu"],
			[13, "relu"],
			[14, "relu"],
			[15, "add"],
		],
		note: "TorchDynamo traces Python bytecode with FakeTensors. Sizes are SymInts: s77 is x.size(0), and the symbols are graph inputs. 2*s77 is an ordinary node, and every value carries its symbolic type.",
	},
	{
		id: "real",
		label: "make_fx real",
		tool: 'make_fx(f, tracing_mode="real")(x, w).code',
		lang: "python",
		code: "def forward(self, x_1, w_1):\n    mm = torch.ops.aten.mm.default(x_1, w_1);  x_1 = w_1 = None\n    view = torch.ops.aten.view.default(mm, [12, -1]);  mm = None\n    relu = torch.ops.aten.relu.default(view);  view = None\n    add = torch.ops.aten.add.Tensor(relu, 6);  relu = None\n    return add\n",
		marks: [
			[1, "mm"],
			[2, "mm"],
			[3, "reshape"],
			[4, "relu"],
			[5, "add"],
		],
		note: "make_fx traces at the ATen level with real tensors. Sizes are plain ints, so x.shape[0] * 2 was baked in as 12 and x.shape[0] as 6.",
	},
	{
		id: "sym",
		label: "make_fx symbolic",
		tool: 'make_fx(f, tracing_mode="symbolic")(x, w)',
		lang: "python",
		code: 'class f(torch.nn.Module):\n    def forward(self, x_1: "f32[s75, s96]", w_1: "f32[s96, s9]"):\n        mm: "f32[s75, s9]" = torch.ops.aten.mm.default(x_1, w_1);  w_1 = None\n        sym_size_int: "Sym(s75)" = torch.ops.aten.sym_size.int(x_1, 0);  x_1 = None\n        mul: "Sym(2*s75)" = sym_size_int * 2\n        view: "f32[2*s75, (s9//2)]" = torch.ops.aten.view.default(mm, [mul, -1]);  mm = mul = None\n        relu: "f32[2*s75, (s9//2)]" = torch.ops.aten.relu.default(view);  view = None\n        add: "f32[2*s75, (s9//2)]" = torch.ops.aten.add.Tensor(relu, sym_size_int);  relu = sym_size_int = None\n        return add',
		marks: [
			[2, "mm"],
			[3, "shape"],
			[4, "shape"],
			[5, "mm"],
			[6, "reshape"],
			[7, "relu"],
			[8, "add"],
		],
		note: "The same ATen graph with FakeTensors and symbolic sizes. The size is read back with aten.sym_size.int, and the multiply is an operator.mul node on SymInts.",
	},
	{
		id: "export",
		label: "torch.export",
		tool: 'export(M(), (x, w), dynamic_shapes={"x": {0: batch}})',
		lang: "python",
		code: 'class GraphModule(torch.nn.Module):\n    def forward(self, x: "f32[s77, 8]", w: "f32[8, 4]"):\n        sym_size_int_1: "Sym(s77)" = torch.ops.aten.sym_size.int(x, 0)\n\n        # return f(x, w)\n        matmul: "f32[s77, 4]" = torch.ops.aten.matmul.default(x, w);  x = w = None\n        mul: "Sym(2*s77)" = sym_size_int_1 * 2\n        reshape: "f32[2*s77, 2]" = torch.ops.aten.reshape.default(matmul, [mul, -1]);  matmul = mul = None\n        relu: "f32[2*s77, 2]" = torch.ops.aten.relu.default(reshape);  reshape = None\n        add: "f32[2*s77, 2]" = torch.ops.aten.add.Tensor(relu, sym_size_int_1);  relu = sym_size_int_1 = None\n        return (add,)',
		marks: [
			[2, "shape"],
			[5, "mm"],
			[6, "shape"],
			[7, "mm"],
			[8, "reshape"],
			[9, "relu"],
			[10, "add"],
		],
		note: "torch.export marks only dimension 0 of x dynamic, so every other size is a constant. The symbol keeps its range, {s77: VR[2, 1024]}.",
	},
];

export const tracerTags: StageTag[] = [
	{
		tag: "mm",
		label: "x @ w",
	},
	{
		tag: "reshape",
		label: "reshape",
	},
	{
		tag: "relu",
		label: "relu",
	},
	{
		tag: "add",
		label: "+ x.shape[0]",
	},
	{
		tag: "shape",
		label: "size arithmetic",
	},
];

export const dynamoShapes: SymbolicShapesData = {
	symbols: [
		{
			name: "s77",
			source: "x.size(0)",
		},
		{
			name: "s27",
			source: "x.size(1) = w.size(0)",
		},
		{
			name: "s21",
			source: "w.size(1)",
		},
	],
	configs: [
		{
			label: "x 6×8, w 8×4",
			values: {
				s77: 6,
				s27: 8,
				s21: 4,
			},
			recompiles: false,
		},
		{
			label: "x 10×8, w 8×4",
			values: {
				s77: 10,
				s27: 8,
				s21: 4,
			},
			recompiles: false,
		},
		{
			label: "x 3×16, w 16×6",
			values: {
				s77: 3,
				s27: 16,
				s21: 6,
			},
			recompiles: false,
		},
		{
			label: "x 1×8, w 8×4",
			values: {
				s77: 1,
				s27: 8,
				s21: 4,
			},
			recompiles: true,
		},
		{
			label: "x 6×8, w 8×2",
			values: {
				s77: 6,
				s27: 8,
				s21: 2,
			},
			recompiles: true,
		},
	],
	rows: [
		{
			name: "s77",
			op: "placeholder",
			code: "input s77",
			symbolic: "Sym(s77)",
			concrete: ["Sym(6)", "Sym(10)", "Sym(3)", "Sym(1)", "Sym(6)"],
		},
		{
			name: "s27",
			op: "placeholder",
			code: "input s27",
			symbolic: "Sym(s27)",
			concrete: ["Sym(8)", "Sym(8)", "Sym(16)", "Sym(8)", "Sym(8)"],
		},
		{
			name: "l_x_",
			op: "placeholder",
			code: "input L_x_",
			symbolic: "f32[s77, s27]",
			concrete: [
				"f32[6, 8]",
				"f32[10, 8]",
				"f32[3, 16]",
				"f32[1, 8]",
				"f32[6, 8]",
			],
		},
		{
			name: "s21",
			op: "placeholder",
			code: "input s21",
			symbolic: "Sym(s21)",
			concrete: ["Sym(4)", "Sym(4)", "Sym(6)", "Sym(4)", "Sym(2)"],
		},
		{
			name: "l_w_",
			op: "placeholder",
			code: "input L_w_",
			symbolic: "f32[s27, s21]",
			concrete: [
				"f32[8, 4]",
				"f32[8, 4]",
				"f32[16, 6]",
				"f32[8, 4]",
				"f32[8, 2]",
			],
		},
		{
			name: "y",
			op: "call_function",
			code: "l_x_ @ l_w_",
			symbolic: "f32[s77, s21]",
			concrete: [
				"f32[6, 4]",
				"f32[10, 4]",
				"f32[3, 6]",
				"f32[1, 4]",
				"f32[6, 2]",
			],
		},
		{
			name: "mul",
			op: "call_function",
			code: "s77 * 2",
			symbolic: "Sym(2*s77)",
			concrete: ["Sym(12)", "Sym(20)", "Sym(6)", "Sym(2)", "Sym(12)"],
		},
		{
			name: "y_1",
			op: "call_method",
			code: "y.reshape(mul, -1)",
			symbolic: "f32[2*s77, (s21//2)]",
			concrete: [
				"f32[12, 2]",
				"f32[20, 2]",
				"f32[6, 3]",
				"f32[2, 2]",
				"f32[12, 1]",
			],
		},
		{
			name: "relu",
			op: "call_function",
			code: "torch.relu(y_1)",
			symbolic: "f32[2*s77, (s21//2)]",
			concrete: [
				"f32[12, 2]",
				"f32[20, 2]",
				"f32[6, 3]",
				"f32[2, 2]",
				"f32[12, 1]",
			],
		},
		{
			name: "add",
			op: "call_function",
			code: "relu + s77",
			symbolic: "f32[2*s77, (s21//2)]",
			concrete: [
				"f32[12, 2]",
				"f32[20, 2]",
				"f32[6, 3]",
				"f32[2, 2]",
				"f32[12, 1]",
			],
		},
	],
	guards: [
		{
			expr: "Eq(Mod(s21*s77, 2*s77), 0)",
			why: "reshape: the element count divides evenly into 2*s77 rows",
			holds: [true, true, true, true, true],
		},
		{
			expr: "Eq(s21*s77, 2*s77*((s21//2)))",
			why: "reshape: the element count divides evenly into 2*s77 rows",
			holds: [true, true, true, true, true],
		},
		{
			expr: "Ne(s21*s77, 2*s77)",
			why: "reshape: the -1 dimension is not inferred as 1",
			holds: [true, true, true, true, false],
		},
		{
			expr: "Ne((s21//2), 1)",
			why: "broadcasting relu(y) + s77: the last dimension is not 1",
			holds: [true, true, true, true, false],
		},
		{
			expr: "2 <= s77",
			why: "0/1 specialization: a symbol is never 0 or 1",
			holds: [true, true, true, false, true],
		},
		{
			expr: "2 <= s27",
			why: "0/1 specialization: a symbol is never 0 or 1",
			holds: [true, true, true, true, true],
		},
		{
			expr: "2 <= s21",
			why: "0/1 specialization: a symbol is never 0 or 1",
			holds: [true, true, true, true, true],
		},
		{
			expr: "x.size(1) == w.size(0)",
			why: "duck sizing: both were 8 when traced, so they share the symbol s27",
			holds: [true, true, true, true, true],
		},
	],
};

export const symNodes: GraphNode[] = [
	{
		id: "node",
		title: "Node y_1",
		subtitle: "call_method · reshape",
		icon: {
			text: "me",
			bg: "#b33b5e",
			fg: "#ffffff",
		},
		note: "The FX node for y.reshape(mul, -1). Its meta dict holds the traced value under example_value (Dynamo) or val (make_fx, export).",
	},
	{
		id: "fake",
		title: "FakeTensor",
		subtitle: "f32[2*s77, (s21//2)]",
		icon: {
			text: "T",
			bg: "#5f7380",
			fg: "#ffffff",
		},
		note: "A tensor with no data. Its shape is ('2*s77', '(s21//2)') and its stride is ('(s21//2)', '1'): every entry is a SymInt.",
	},
	{
		id: "symint",
		title: "SymInt",
		subtitle: "shape[1] = (s21//2)",
		icon: {
			text: "int",
			bg: "#2f8a5b",
			fg: "#ffffff",
		},
		note: "Behaves like a Python int. Every operator on it (+, *, //, ==, <) is forwarded to its SymNode.",
	},
	{
		id: "symnode",
		title: "SymNode",
		subtitle: "pytype=int, hint=2",
		icon: {
			text: "N",
			bg: "#b8742a",
			fg: "#ffffff",
		},
		note: "Holds the sympy expression, the hint 2 (the value in this trace, from s21 = 4) and a pointer to the ShapeEnv.",
	},
	{
		id: "expr",
		title: "(s21//2)",
		subtitle: "sympy FloorDiv(s21, 2)",
		icon: {
			text: "∑",
			bg: "#7a62b8",
			fg: "#ffffff",
		},
		note: "The size as a sympy expression over the input symbols. FloorDiv is PyTorch's own sympy function for Python's //.",
	},
	{
		id: "env",
		title: "ShapeEnv",
		subtitle: "3 symbols · 4 guards",
		icon: {
			text: "E",
			bg: "#2f6fb0",
			fg: "#ffffff",
		},
		note: "One per trace. backed_var_to_val = s77: 6, s27: 8, s21: 4; var_to_range gives each symbol [2, int_oo]; guards lists every condition the trace relied on.",
	},
];

export const symEdges: GraphEdge[] = [
	{
		from: "node",
		to: "fake",
	},
	{
		from: "fake",
		to: "symint",
	},
	{
		from: "symint",
		to: "symnode",
	},
	{
		from: "symnode",
		to: "expr",
	},
	{
		from: "symnode",
		to: "env",
	},
];
