// Generated by a scratch script (emit.py) from jax 0.11.2 (git 32544801) on CPU. Do not edit by hand.
// It traced, transformed and compiled the post's running example (loss on a 3x2 x, see
// modelSource) and asserted that every value below matches jax.jvp, jax.linearize, jax.vjp and
// jax.grad. Jaxprs are printed with width=104 so each equation sits on one line. In the compiled
// HLO, metadata={...} attributes and the source-location tables are removed.

export const modelSource: string[] = [
	"import jax.numpy as jnp",
	"",
	"def predict(w, x):",
	"    return jnp.tanh(x @ w)",
	"",
	"def loss(w, x, y):",
	"    err = predict(w, x) - y",
	"    return jnp.mean(err ** 2)",
];
export const traceLog: { prim: string; added: number; src: number[] }[] = [
	{
		prim: "dot_general",
		added: 1,
		src: [3, 6],
	},
	{
		prim: "tanh",
		added: 1,
		src: [3, 6],
	},
	{
		prim: "sub",
		added: 1,
		src: [6],
	},
	{
		prim: "integer_pow",
		added: 1,
		src: [7],
	},
	{
		prim: "convert_element_type",
		added: 0,
		src: [7],
	},
	{
		prim: "reduce_sum",
		added: 1,
		src: [7],
	},
	{
		prim: "div",
		added: 1,
		src: [7],
	},
];
export const lossJaxpr: string[] = [
	"{ lambda ; a:f32[2] b:f32[3,2] c:f32[3]. let",
	"    d:f32[3] = dot_general[dimension_numbers=(([1], [0]), ([], [])) preferred_element_type=float32] b a",
	"    e:f32[3] = tanh d",
	"    f:f32[3] = sub e c",
	"    g:f32[3] = integer_pow[y=2] f",
	"    h:f32[] = reduce_sum[axes=(0,) out_sharding=None] g",
	"    i:f32[] = div h 3.0:f32[]",
	"  in (i,) }",
];
export const jvpJaxpr: string[] = [
	"{ lambda a:f32[3,2] b:f32[3]; c:f32[2] d:f32[2]. let",
	"    e:f32[3] = dot_general[dimension_numbers=(([1], [0]), ([], [])) preferred_element_type=float32] a c",
	"    f:f32[3] = dot_general[dimension_numbers=(([1], [0]), ([], [])) preferred_element_type=float32] a d",
	"    g:f32[3] = tanh e",
	"    h:f32[3] = one_minus_square g",
	"    i:f32[3] = mul f h",
	"    j:f32[3] = sub g b",
	"    k:f32[3] = integer_pow[y=2] j",
	"    l:f32[3] = mul 2.0:f32[] j",
	"    m:f32[3] = mul i l",
	"    n:f32[] = reduce_sum[axes=(0,) out_sharding=None] k",
	"    o:f32[] = reduce_sum[axes=(0,) out_sharding=None] m",
	"    p:f32[] = div n 3.0:f32[]",
	"    q:f32[] = div o 3.0:f32[]",
	"  in (p, q) }",
];
export const linJaxpr: string[] = [
	"{ lambda a:f32[3,2] b:f32[3] c:f32[3]; d:f32[2]. let",
	"    e:f32[3] = dot_general[dimension_numbers=(([1], [0]), ([], [])) preferred_element_type=float32] a d",
	"    f:f32[3] = mul e b",
	"    g:f32[3] = mul f c",
	"    h:f32[] = reduce_sum[axes=(0,) out_sharding=None] g",
	"    i:f32[] = div h 3.0:f32[]",
	"  in (i,) }",
];
export const vjpJaxpr: string[] = [
	"{ lambda a:f32[3] b:f32[3] c:f32[3,2]; d:f32[]. let",
	"    e:f32[] = div d 3.0:f32[]",
	"    f:f32[3] = broadcast_in_dim e",
	"    g:f32[3] = mul f a",
	"    h:f32[3] = mul g b",
	"    i:f32[2] = dot_general[dimension_numbers=(([0], [0]), ([], [])) preferred_element_type=float32] h c",
	"  in (i,) }",
];
export const gradJaxpr: string[] = [
	"{ lambda ; a:f32[2] b:f32[3,2] c:f32[3]. let",
	"    d:f32[3] = dot_general[dimension_numbers=(([1], [0]), ([], [])) preferred_element_type=float32] b a",
	"    e:f32[3] = tanh d",
	"    f:f32[3] = one_minus_square e",
	"    g:f32[3] = sub e c",
	"    h:f32[3] = integer_pow[y=2] g",
	"    i:f32[3] = mul 2.0:f32[] g",
	"    j:f32[] = reduce_sum[axes=(0,) out_sharding=None] h",
	"    _:f32[] = div j 3.0:f32[]",
	"    k:f32[] = div 1.0:f32[] 3.0:f32[]",
	"    l:f32[3] = broadcast_in_dim k",
	"    m:f32[3] = mul l i",
	"    n:f32[3] = mul m f",
	"    o:f32[2] = dot_general[dimension_numbers=(([0], [0]), ([], [])) preferred_element_type=float32] n b",
	"  in (o,) }",
];
export const values: Record<string, string> = {
	x: "[[1.0000, 2.0000], [3.0000, 4.0000], [5.0000, 6.0000]]",
	w: "[0.1000, -0.2000]",
	y: "[0.0000, 1.0000, 0.0000]",
	t: "[1.0000, 0.0000]",
	d: "[-0.3000, -0.5000, -0.7000]",
	e: "[-0.2913, -0.4621, -0.6044]",
	f: "[-0.2913, -1.4621, -0.6044]",
	g: "[0.0849, 2.1378, 0.3653]",
	h: "2.5879",
	i: "0.8626",
	dDot: "[1.0000, 3.0000, 5.0000]",
	eDot: "[0.9151, 2.3593, 3.1737]",
	fDot: "[0.9151, 2.3593, 3.1737]",
	gDot: "[-0.5332, -6.8993, -3.8362]",
	hDot: "-11.2686",
	iDot: "-3.7562",
	resA: "[[1.0000, 2.0000], [3.0000, 4.0000], [5.0000, 6.0000]]",
	resB: "[0.9151, 0.7864, 0.6347]",
	resC: "[-0.5826, -2.9242, -1.2087]",
	ctI: "1.0000",
	ctH: "0.3333",
	ctG: "[0.3333, 0.3333, 0.3333]",
	ctF: "[-0.1942, -0.9747, -0.4029]",
	ctE: "[-0.1777, -0.7666, -0.2557]",
	ctW: "[-3.7562, -4.9563]",
};
export const stablehloLoss: string =
	'module @jit_loss attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {\n  func.func public @main(%arg0: tensor<2xf32>, %arg1: tensor<3x2xf32>, %arg2: tensor<3xf32>) -> (tensor<f32> {jax.result_info = "result"}) {\n    %0 = stablehlo.dot_general %arg1, %arg0, contracting_dims = [1] x [0], precision = [DEFAULT, DEFAULT] : (tensor<3x2xf32>, tensor<2xf32>) -> tensor<3xf32>\n    %1 = stablehlo.tanh %0 : tensor<3xf32>\n    %2 = stablehlo.subtract %1, %arg2 : tensor<3xf32>\n    %3 = stablehlo.multiply %2, %2 : tensor<3xf32>\n    %cst = stablehlo.constant dense<0.000000e+00> : tensor<f32>\n    %4 = stablehlo.reduce(%3 init: %cst) applies stablehlo.add across dimensions = [0] : (tensor<3xf32>, tensor<f32>) -> tensor<f32>\n    %cst_0 = stablehlo.constant dense<3.000000e+00> : tensor<f32>\n    %5 = stablehlo.divide %4, %cst_0 : tensor<f32>\n    return %5 : tensor<f32>\n  }\n}';
export const hloLoss: string =
	"HloModule jit_loss, is_scheduled=true, entry_computation_layout={(f32[2]{0}, f32[3,2]{1,0}, f32[3]{0})->f32[]}\n\n%region_0.1 (reduce_sum.3: f32[], reduce_sum.4: f32[]) -> f32[] {\n  %reduce_sum.3 = f32[] parameter(0)\n  %reduce_sum.4 = f32[] parameter(1)\n  ROOT %reduce_sum.5 = f32[] add(%reduce_sum.3, %reduce_sum.4)\n}\n\n%fused_computation (param_0.5: f32[3], param_1.5: f32[3,1]) -> f32[] {\n  %param_1.5 = f32[3,1]{1,0} parameter(1)\n  %bitcast.2 = f32[3]{0} bitcast(%param_1.5)\n  %tanh.0 = f32[3]{0} tanh(%bitcast.2)\n  %param_0.5 = f32[3]{0} parameter(0)\n  %sub.0 = f32[3]{0} subtract(%tanh.0, %param_0.5)\n  %integer_pow.0 = f32[3]{0} multiply(%sub.0, %sub.0)\n  %constant.4 = f32[] constant(0)\n  %reduce_sum.0 = f32[] reduce(%integer_pow.0, %constant.4), dimensions={0}, to_apply=%region_0.1\n  %constant.1 = f32[] constant(0.333333343)\n  ROOT %multiply.1 = f32[] multiply(%reduce_sum.0, %constant.1)\n}\n\nENTRY %main.2 (w.1: f32[2], x.1: f32[3,2], y.1: f32[3]) -> f32[] {\n  %w.1 = f32[2]{0} parameter(0)\n  %x.1 = f32[3,2]{1,0} parameter(1)\n  %y.1 = f32[3]{0} parameter(2)\n  %bitcast = f32[2,1]{1,0} bitcast(%w.1)\n  %dot = f32[3,1]{1,0} dot(%x.1, %bitcast), lhs_contracting_dims={1}, rhs_contracting_dims={0}\n  ROOT %reduce_multiply_fusion = f32[] fusion(%y.1, %dot), kind=kLoop, calls=%fused_computation\n}";
export const stablehloGrad: string =
	'module @jit_loss attributes {mhlo.num_partitions = 1 : i32, mhlo.num_replicas = 1 : i32} {\n  func.func public @main(%arg0: tensor<2xf32>, %arg1: tensor<3x2xf32>, %arg2: tensor<3xf32>) -> (tensor<2xf32> {jax.result_info = "result"}) {\n    %0 = stablehlo.dot_general %arg1, %arg0, contracting_dims = [1] x [0], precision = [DEFAULT, DEFAULT] : (tensor<3x2xf32>, tensor<2xf32>) -> tensor<3xf32>\n    %1 = stablehlo.tanh %0 : tensor<3xf32>\n    %cst = stablehlo.constant dense<1.000000e+00> : tensor<f32>\n    %2 = stablehlo.broadcast_in_dim %cst, dims = [] : (tensor<f32>) -> tensor<3xf32>\n    %3 = stablehlo.add %2, %1 : tensor<3xf32>\n    %cst_0 = stablehlo.constant dense<1.000000e+00> : tensor<f32>\n    %4 = stablehlo.broadcast_in_dim %cst_0, dims = [] : (tensor<f32>) -> tensor<3xf32>\n    %5 = stablehlo.subtract %4, %1 : tensor<3xf32>\n    %6 = stablehlo.multiply %3, %5 : tensor<3xf32>\n    %7 = stablehlo.subtract %1, %arg2 : tensor<3xf32>\n    %cst_1 = stablehlo.constant dense<2.000000e+00> : tensor<f32>\n    %8 = stablehlo.broadcast_in_dim %cst_1, dims = [] : (tensor<f32>) -> tensor<3xf32>\n    %9 = stablehlo.multiply %8, %7 : tensor<3xf32>\n    %cst_2 = stablehlo.constant dense<1.000000e+00> : tensor<f32>\n    %cst_3 = stablehlo.constant dense<3.000000e+00> : tensor<f32>\n    %10 = stablehlo.divide %cst_2, %cst_3 : tensor<f32>\n    %11 = stablehlo.broadcast_in_dim %10, dims = [] : (tensor<f32>) -> tensor<3xf32>\n    %12 = stablehlo.multiply %11, %9 : tensor<3xf32>\n    %13 = stablehlo.multiply %12, %6 : tensor<3xf32>\n    %14 = stablehlo.dot_general %13, %arg1, contracting_dims = [0] x [0], precision = [DEFAULT, DEFAULT] : (tensor<3xf32>, tensor<3x2xf32>) -> tensor<2xf32>\n    return %14 : tensor<2xf32>\n  }\n}';
export const hloGrad: string =
	"HloModule jit_loss, is_scheduled=true, entry_computation_layout={(f32[2]{0}, f32[3,2]{1,0}, f32[3]{0})->f32[2]{0}}\n\n%fused_computation (param_0.3: f32[3], param_1.7: f32[3,1]) -> f32[3,1] {\n  %param_1.7 = f32[3,1]{1,0} parameter(1)\n  %bitcast.5 = f32[3]{0} bitcast(%param_1.7)\n  %tanh.0 = f32[3]{0} tanh(%bitcast.5)\n  %param_0.3 = f32[3]{0} parameter(0)\n  %sub.1 = f32[3]{0} subtract(%tanh.0, %param_0.3)\n  %constant.2 = f32[] constant(0.666666687)\n  %broadcast.2 = f32[3]{0} broadcast(%constant.2), dimensions={}\n  %broadcast_in_dim.0 = f32[3]{0} multiply(%sub.1, %broadcast.2)\n  %constant.1 = f32[] constant(1)\n  %broadcast.1 = f32[3]{0} broadcast(%constant.1), dimensions={}\n  %add.0 = f32[3]{0} add(%tanh.0, %broadcast.1)\n  %sub.0 = f32[3]{0} subtract(%broadcast.1, %tanh.0)\n  %mul.1 = f32[3]{0} multiply(%add.0, %sub.0)\n  %mul.0 = f32[3]{0} multiply(%broadcast_in_dim.0, %mul.1)\n  ROOT %bitcast.4 = f32[3,1]{1,0} bitcast(%mul.0)\n}\n\nENTRY %main.1 (w.1: f32[2], x.1: f32[3,2], y.1: f32[3]) -> f32[2] {\n  %w.1 = f32[2]{0} parameter(0)\n  %x.1 = f32[3,2]{1,0} parameter(1)\n  %y.1 = f32[3]{0} parameter(2)\n  %bitcast = f32[2,1]{1,0} bitcast(%w.1)\n  %dot = f32[3,1]{1,0} dot(%x.1, %bitcast), lhs_contracting_dims={1}, rhs_contracting_dims={0}\n  %multiply_bitcast_fusion = f32[3,1]{1,0} fusion(%y.1, %dot), kind=kLoop, calls=%fused_computation\n  %dot.1 = f32[1,2]{1,0} dot(%multiply_bitcast_fusion, %x.1), lhs_contracting_dims={0}, rhs_contracting_dims={0}\n  ROOT %bitcast.3 = f32[2]{0} bitcast(%dot.1)\n}";
