// How a Triton kernel generated by Inductor covers its iteration space, for KernelBlocks.astro.
//
// The iteration space is rows x cols. Each program (one thread block) handles a block of
// blockRows x blockCols elements: program p along an axis starts at p * BLOCK, and lanes past
// the end are masked off (xmask / ymask in the generated code). Every pointer the kernel loads
// from or stores to maps an element (r, c) to the offset r * strides[0] + c * strides[1]. The
// figure draws the blocks over the grid and, for the selected program, the offsets it touches
// in each buffer, which shows whether its accesses are contiguous (coalesced) or strided.
//
// Program ids follow the generated code: with a single column of blocks (a reduction kernel,
// whose blocks span the whole row) program_id(0) runs over rows; otherwise program_id(0) runs
// over columns (x) and program_id(1) over rows (y).

export interface Pointer {
	name: string;
	strides: [number, number];
}

export interface BlocksConfig {
	rows: number;
	cols: number;
	pointers: Pointer[];
	/** Names of the row and column index variables in the kernel, e.g. "x0" and "r0_1". */
	rowVar: string;
	colVar: string;
}

export interface Program {
	label: string;
	/** Block coordinates: block row, block column. */
	br: number;
	bc: number;
}

export function programs(
	rows: number,
	cols: number,
	bR: number,
	bC: number,
): Program[] {
	const nR = Math.ceil(rows / bR);
	const nC = Math.ceil(cols / bC);
	const out: Program[] = [];
	for (let br = 0; br < nR; br++)
		for (let bc = 0; bc < nC; bc++) {
			const label =
				nC === 1 ? `pid ${br}` : nR === 1 ? `pid ${bc}` : `pid (${bc}, ${br})`;
			out.push({ label, br, bc });
		}
	return out;
}

/** Elements of a program's block: in range, and masked (past the end of rows or cols). */
export function blockCells(
	cfg: BlocksConfig,
	p: Program,
	bR: number,
	bC: number,
): { live: [number, number][]; masked: [number, number][] } {
	const live: [number, number][] = [];
	const masked: [number, number][] = [];
	for (let r = p.br * bR; r < (p.br + 1) * bR; r++)
		for (let c = p.bc * bC; c < (p.bc + 1) * bC; c++)
			(r < cfg.rows && c < cfg.cols ? live : masked).push([r, c]);
	return { live, masked };
}

export const offsetOf = (ptr: Pointer, r: number, c: number) =>
	r * ptr.strides[0] + c * ptr.strides[1];

/** Sorted offsets grouped into runs of consecutive addresses. */
export function runs(offsets: number[]): [number, number][] {
	const s = [...new Set(offsets)].sort((a, b) => a - b);
	const out: [number, number][] = [];
	for (const o of s) {
		const last = out[out.length - 1];
		if (last && o === last[1] + 1) last[1] = o;
		else out.push([o, o]);
	}
	return out;
}

export function describeRuns(rs: [number, number][]): string {
	const len = rs[0] ? rs[0][1] - rs[0][0] + 1 : 0;
	const same = rs.every(([a, b]) => b - a + 1 === len);
	const list = rs.map(([a, b]) => (a === b ? `${a}` : `${a}–${b}`)).join(", ");
	const head =
		rs.length === 1
			? `1 contiguous run of ${len}`
			: same
				? `${rs.length} runs of ${len}`
				: `${rs.length} runs`;
	return rs.length <= 8 ? `${head}: ${list}` : head;
}

const hueOf = (k: number) => (25 + k * 137.508) % 360;
const CELL = 13;
const STRIP = 10;

export interface BlocksState {
	block: [number, number];
	pid: number;
}

/** The figure as an SVG string: grid with blocks on top, one memory strip per pointer below. */
export function drawBlocks(
	cfg: BlocksConfig,
	st: BlocksState,
	wrap = 16,
): string {
	const [bR, bC] = st.block;
	const progs = programs(cfg.rows, cfg.cols, bR, bC);
	const sel = progs[Math.min(st.pid, progs.length - 1)];
	const padR = Math.ceil(cfg.rows / bR) * bR - cfg.rows;
	const padC = Math.ceil(cfg.cols / bC) * bC - cfg.cols;
	const left = 34;
	const top = 18;
	const gridW = (cfg.cols + padC) * CELL;
	const gridH = (cfg.rows + padR) * CELL;
	const owner = (r: number, c: number) =>
		Math.floor(r / bR) * Math.ceil(cfg.cols / bC) + Math.floor(c / bC);
	const parts: string[] = [];

	parts.push(
		`<text class="axis" x="${left - 6}" y="${top - 6}" text-anchor="end">${cfg.rowVar}↓</text>`,
		`<text class="axis" x="${left}" y="${top - 6}">${cfg.colVar}→</text>`,
	);
	for (let r = 0; r < cfg.rows; r++)
		for (let c = 0; c < cfg.cols; c++) {
			const k = owner(r, c);
			const on = k === progs.indexOf(sel);
			parts.push(
				`<rect class="cell${on ? " on" : ""}" data-pid="${k}" x="${left + c * CELL}" y="${top + r * CELL}" width="${CELL - 1}" height="${CELL - 1}" style="--hue:${hueOf(k).toFixed(1)}"/>`,
			);
		}
	const { live, masked } = blockCells(cfg, sel, bR, bC);
	for (const [r, c] of masked)
		parts.push(
			`<rect class="cell masked" x="${left + c * CELL}" y="${top + r * CELL}" width="${CELL - 1}" height="${CELL - 1}"/>`,
		);
	parts.push(
		`<rect class="block" x="${left + sel.bc * bC * CELL - 1}" y="${top + sel.br * bR * CELL - 1}" width="${bC * CELL + 1}" height="${bR * CELL + 1}"/>`,
	);
	for (let r = 0; r < cfg.rows; r += Math.max(1, Math.ceil(cfg.rows / 8)))
		parts.push(
			`<text class="tick end" x="${left - 4}" y="${top + r * CELL + 9}">${r}</text>`,
		);

	let y = top + gridH + 26;
	const stripW = wrap * STRIP;
	for (const ptr of cfg.pointers) {
		const size = cfg.rows * cfg.cols;
		const touched = new Set(live.map(([r, c]) => offsetOf(ptr, r, c)));
		parts.push(`<text class="ptr" x="${left}" y="${y - 5}">${ptr.name}</text>`);
		for (let o = 0; o < size; o++) {
			const x = left + (o % wrap) * STRIP;
			const yy = y + Math.floor(o / wrap) * STRIP;
			parts.push(
				`<rect class="mem${touched.has(o) ? " on" : ""}" x="${x}" y="${yy}" width="${STRIP - 1}" height="${STRIP - 1}" style="--hue:${hueOf(progs.indexOf(sel)).toFixed(1)}"/>`,
			);
		}
		y += Math.ceil(size / wrap) * STRIP + 22;
	}
	const width = Math.max(left + gridW, left + stripW) + 6;
	const height = y - 12;
	return `<svg viewBox="0 0 ${width} ${height}" width="${Math.round(width * 1.25)}" height="${Math.round(height * 1.25)}" role="img" aria-label="Triton programs over a ${cfg.rows} by ${cfg.cols} iteration space">${parts.join("")}</svg>`;
}

/** One line per pointer: the runs of offsets the selected program touches. */
export function describeProgram(cfg: BlocksConfig, st: BlocksState): string[] {
	const [bR, bC] = st.block;
	const progs = programs(cfg.rows, cfg.cols, bR, bC);
	const sel = progs[Math.min(st.pid, progs.length - 1)];
	const { live, masked } = blockCells(cfg, sel, bR, bC);
	const lines = [
		`${sel.label} of ${progs.length}: ${live.length} element${live.length === 1 ? "" : "s"}${masked.length ? `, ${masked.length} masked lane${masked.length === 1 ? "" : "s"}` : ""}`,
	];
	for (const ptr of cfg.pointers)
		lines.push(
			`${ptr.name}: ${describeRuns(runs(live.map(([r, c]) => offsetOf(ptr, r, c))))}`,
		);
	return lines;
}
