// Figure data for the hard-system-design-problems post. The diagrams reuse BoxDiagram and
// SequenceSteps from the payments visualisation library. All capacities match the worked
// examples in the post.

import type { GraphEdge, GraphNode } from "../graph/dependencyGraph";
import type { BoxEdge, BoxNode } from "../payments/boxDiagram";
import type { Message, Participant } from "../payments/sequence";

export const idNodes: BoxNode[] = [
	{
		id: "api1",
		label: "API node 17",
		sub: "worker 17",
		col: 0,
		row: 0,
		group: 1,
		note: "This worker owns one stable 10-bit worker ID. It never asks another node for permission before issuing an ID.",
	},
	{
		id: "api2",
		label: "API node 42",
		sub: "worker 42",
		col: 0,
		row: 2,
		group: 1,
		note: "A different worker ID keeps this node's sequence space disjoint, even in the same millisecond.",
	},
	{
		id: "clock1",
		label: "Clock",
		sub: "1,735,689,600,123 ms",
		col: 1,
		row: 0,
		group: 0,
	},
	{
		id: "clock2",
		label: "Clock",
		sub: "1,735,689,600,123 ms",
		col: 1,
		row: 2,
		group: 0,
	},
	{
		id: "pack1",
		label: "Pack 64 bits",
		sub: "41 time · 10 worker · 12 seq",
		col: 2,
		row: 0,
		group: 3,
		note: "The timestamp makes IDs roughly time-ordered. The worker and sequence fields make IDs unique without coordination.",
	},
	{
		id: "pack2",
		label: "Pack 64 bits",
		sub: "41 time · 10 worker · 12 seq",
		col: 2,
		row: 2,
		group: 3,
	},
	{
		id: "id1",
		label: "ID",
		sub: "... 010001 · 000000000000",
		col: 3,
		row: 0,
		group: 4,
	},
	{
		id: "id2",
		label: "ID",
		sub: "... 101010 · 000000000000",
		col: 3,
		row: 2,
		group: 4,
	},
];

export const idEdges: BoxEdge[] = [
	{ from: "api1", to: "clock1" },
	{ from: "clock1", to: "pack1" },
	{ from: "pack1", to: "id1" },
	{ from: "api2", to: "clock2" },
	{ from: "clock2", to: "pack2" },
	{ from: "pack2", to: "id2" },
];

export const feedNodes: BoxNode[] = [
	{
		id: "post",
		label: "Post service",
		sub: "store post once",
		col: 0,
		row: 1,
		group: 1,
		note: "The durable post body is stored once. Timelines contain only compact post IDs and scores.",
	},
	{
		id: "fan",
		label: "Fan-out workers",
		sub: "ordinary authors",
		col: 1,
		row: 0,
		group: 3,
		note: "For an ordinary author, workers append the post ID to each active follower's home-timeline cache.",
	},
	{
		id: "author",
		label: "Author outbox",
		sub: "celebrity posts",
		col: 1,
		row: 2,
		group: 4,
		note: "Celebrity posts stay in the author's outbox. One write replaces tens of millions of writes to follower timelines.",
	},
	{
		id: "home",
		label: "Home timelines",
		sub: "precomputed IDs",
		col: 2,
		row: 0,
		group: 3,
		note: "Reads from ordinary authors are already materialized, so opening the app is a bounded cache lookup.",
	},
	{
		id: "merge",
		label: "Read-time merge",
		sub: "home + celebrity outboxes",
		col: 2,
		row: 2,
		group: 2,
		note: "At read time, merge the cached home timeline with recent posts from the few celebrity accounts this reader follows.",
	},
	{
		id: "rank",
		label: "Rank + hydrate",
		sub: "top K, then fetch bodies",
		col: 3,
		row: 1,
		group: 5,
		note: "Rank IDs first. Fetch full post bodies and media metadata only for the final page, avoiding work for discarded candidates.",
	},
];

export const feedEdges: BoxEdge[] = [
	{ from: "post", to: "fan", label: "normal" },
	{ from: "post", to: "author", label: "celebrity" },
	{ from: "fan", to: "home", label: "push" },
	{ from: "home", to: "merge" },
	{ from: "author", to: "merge", label: "pull" },
	{ from: "merge", to: "rank" },
];

export const ticketParticipants: Participant[] = [
	{ id: "a", label: "Buyer A" },
	{ id: "b", label: "Buyer B" },
	{ id: "api", label: "Reservation API" },
	{ id: "db", label: "Inventory DB" },
	{ id: "pay", label: "Payment" },
];

export const ticketMessages: Message[] = [
	{
		from: "a",
		to: "api",
		label: "hold(seat 7A, request A)",
		step: "A asks",
		note: "Buyer A supplies an idempotency key. The API does not trust a cache to decide ownership; the inventory database is authoritative.",
	},
	{
		from: "b",
		to: "api",
		label: "hold(seat 7A, request B)",
		step: "B asks",
		note: "Buyer B races for the same seat. Both requests may reach different API nodes.",
	},
	{
		from: "api",
		to: "db",
		label: "UPDATE available → held",
		step: "Claim",
		tone: 1,
		note: "One conditional update changes the seat only if it is still <code>available</code>. The database serializes the conflict; exactly one request updates one row.",
	},
	{
		from: "db",
		to: "api",
		label: "A won · token 81 · expires 12:05",
		step: "Lease",
		reply: true,
		tone: 1,
		note: "The winner gets a five-minute hold and a monotonically increasing fencing token. A stale holder cannot later overwrite a newer reservation.",
	},
	{
		from: "api",
		to: "b",
		label: "409 seat unavailable",
		step: "B loses",
		reply: true,
		tone: 2,
		note: "Buyer B loses immediately. Returning a conflict is safer than maintaining two tentative truths and reconciling them later.",
	},
	{
		from: "api",
		to: "pay",
		label: "charge(order A, idempotency key)",
		step: "Pay",
		note: "Payment is outside the database transaction. The order ID is the idempotency key, so a timeout can be retried without a second charge.",
	},
	{
		from: "pay",
		to: "api",
		label: "approved",
		step: "Approved",
		reply: true,
		tone: 1,
		note: "The payment provider reports success. If this reply is lost, reconciliation by idempotency key recovers the result.",
	},
	{
		from: "api",
		to: "db",
		label: "held → sold WHERE token = 81",
		step: "Commit",
		tone: 1,
		note: "The final update includes the fencing token. If A's hold expired and another buyer obtained token 82, this stale update affects zero rows.",
	},
];

export const schedulerNodes: BoxNode[] = [
	{
		id: "api",
		label: "Schedule API",
		sub: "writes job + next_run",
		col: 0,
		row: 0,
		group: 1,
		note: "Creating a schedule is a durable database write. The API also records the time zone and a client idempotency key.",
	},
	{
		id: "db",
		label: "Schedule DB",
		sub: "time-bucketed index",
		col: 1,
		row: 0,
		group: 0,
		note: "Jobs are indexed by the next due time and partition. Pollers claim small batches with row locks instead of scanning every schedule.",
	},
	{
		id: "poll",
		label: "Pollers",
		sub: "SKIP LOCKED claims",
		col: 2,
		row: 0,
		group: 3,
		note: "Several pollers can safely work at once. Locked rows are skipped, so they divide due work instead of waiting behind each other.",
	},
	{
		id: "q",
		label: "Durable queue",
		sub: "at-least-once",
		col: 3,
		row: 0,
		group: 2,
		note: "The queue absorbs bursts and redelivers messages when a consumer crashes. Delivery is deliberately at-least-once.",
	},
	{
		id: "work",
		label: "Workers",
		sub: "lease + heartbeat",
		col: 3,
		row: 2,
		group: 5,
		note: "A worker owns a time-limited lease. If it dies, the message becomes visible and another worker retries the same logical run.",
	},
	{
		id: "target",
		label: "Target service",
		sub: "idempotency key = run_id",
		col: 2,
		row: 2,
		group: 4,
		note: "The target deduplicates by run ID. This is what makes redelivery safe; the queue alone cannot promise an external side effect exactly once.",
	},
];

export const schedulerEdges: BoxEdge[] = [
	{ from: "api", to: "db" },
	{ from: "db", to: "poll", label: "claim due" },
	{ from: "poll", to: "q", label: "run_id" },
	{ from: "q", to: "work", label: "deliver" },
	{ from: "work", to: "target", label: "execute" },
	{ from: "target", to: "work", label: "result", dashed: true },
];

export const hotelParticipants: Participant[] = [
	{ id: "guest", label: "Guest" },
	{ id: "api", label: "Booking API" },
	{ id: "inv", label: "Inventory rows", sub: "property SQL shard" },
	{ id: "pay", label: "Payment" },
	{ id: "book", label: "Booking rows", sub: "same SQL shard" },
];

export const hotelMessages: Message[] = [
	{
		from: "guest",
		to: "api",
		label: "hold(deluxe, Oct 10–13)",
		step: "Hold",
		note: "The guest requests one deluxe room for three nights and supplies an idempotency key. The quoted price is copied into the hold so a later rate change cannot alter checkout.",
	},
	{
		from: "api",
		to: "inv",
		label: "claim Oct 10, 11, 12",
		step: "Claim nights",
		note: "One short transaction conditionally increments <code>held</code> on all three inventory rows. It locks dates in ascending order and commits only if every night has capacity.",
	},
	{
		from: "inv",
		to: "api",
		label: "hold H81 · expires 12:15",
		step: "Lease",
		reply: true,
		tone: 1,
		note: "The durable hold is a 15-minute lease. The database transaction is already closed; no row lock remains while the guest enters payment details.",
	},
	{
		from: "api",
		to: "pay",
		label: "authorize(B91, €540)",
		step: "Pay",
		note: "The booking ID is the payment idempotency key. A timeout can be reconciled without creating a second authorization.",
	},
	{
		from: "pay",
		to: "api",
		label: "approved",
		step: "Approved",
		reply: true,
		tone: 1,
		note: "Payment approval does not by itself create the booking; the service must still consume the matching, unexpired hold.",
	},
	{
		from: "api",
		to: "book",
		label: "create B91; H81 held → booked",
		step: "Book",
		tone: 1,
		note: "In one local transaction, create the booking and nightly booking rows, decrement <code>held</code>, increment <code>booked</code>, mark the hold consumed, and write an outbox event.",
	},
	{
		from: "book",
		to: "guest",
		label: "confirmed · code K7P4Q2",
		step: "Confirm",
		reply: true,
		tone: 1,
		note: "The response contains an opaque confirmation code. Email is asynchronous; the committed booking row is the source of truth.",
	},
];

export const hotelArchitectureNodes: GraphNode[] = [
	{
		id: "client",
		title: "Web / mobile client",
		subtitle: "search, checkout, my trips",
		icon: { text: "UI", bg: "#4a7fe0" },
		note: "The client carries an opaque cursor for lists and an idempotency key for every mutation. It never decides whether inventory is available.",
	},
	{
		id: "edge",
		title: "CDN + API gateway",
		subtitle: "cache, auth, rate limits",
		icon: "hexagon",
		note: "The CDN serves hotel images and cacheable property pages. The gateway authenticates mutations and protects downstream services from bursts.",
	},
	{
		id: "search",
		title: "Search service",
		subtitle: "destination + dates + filters",
		icon: "sparkle",
		note: "Search returns candidates from a denormalized index. Its availability is a hint; quote and hold recheck the authoritative inventory shard.",
	},
	{
		id: "booking",
		title: "Booking service",
		subtitle: "quote, hold, confirm, cancel",
		icon: "fn",
		note: "This service owns the booking state machine. It routes by property ID so every night of a stay and the booking record share one SQL transaction.",
	},
	{
		id: "trips",
		title: "My trips service",
		subtitle: "guest-keyed read API",
		icon: "fn",
		note: "Guest history is served from a guest-keyed read model, avoiding a scatter query across all property shards.",
	},
	{
		id: "index",
		title: "Search index + cache",
		subtitle: "geo, text, facets, price hint",
		icon: { text: "IDX", bg: "#b04fc4" },
		note: "A search engine handles geography, text and facets; a cache absorbs popular destination reads. Both may lag authoritative inventory briefly.",
	},
	{
		id: "sql",
		title: "Property SQL shards",
		subtitle: "inventory, holds, bookings, outbox",
		icon: { text: "SQL", bg: "#2f8a5b" },
		note: "Each property has one home shard. Nightly inventory, holds, booking rows and the transactional outbox commit atomically here.",
	},
	{
		id: "payment",
		title: "Payment provider",
		subtitle: "booking_id is idempotency key",
		icon: { text: "PAY", bg: "#b8742a" },
		note: "Payment cannot join the SQL transaction. Idempotency and reconciliation resolve a crash between authorization and booking confirmation.",
	},
	{
		id: "relay",
		title: "Outbox relay",
		subtitle: "publish committed events",
		icon: "fn",
		note: "The relay retries until the committed outbox event reaches the log. Consumers deduplicate by event ID.",
	},
	{
		id: "log",
		title: "Booking event log",
		subtitle: "durable, replayable",
		icon: { text: "LOG", bg: "#5f7380" },
		note: "Confirmed, modified and cancelled events drive read models and notifications without dual-writing from the booking transaction.",
	},
	{
		id: "guestread",
		title: "Guest booking index",
		subtitle: "guest_id → bookings",
		icon: { text: "KV", bg: "#3178c6" },
		note: "This read model is keyed by guest ID and may be rebuilt from the event log. The property SQL booking remains authoritative.",
	},
	{
		id: "notify",
		title: "Email / partner updates",
		subtitle: "asynchronous consumers",
		icon: "commit",
		note: "Email failure does not roll back a booking. The consumer retries the same event independently.",
	},
];

export const hotelArchitectureEdges: GraphEdge[] = [
	{ from: "client", to: "edge" },
	{ from: "edge", to: "search" },
	{ from: "edge", to: "booking" },
	{ from: "edge", to: "trips" },
	{ from: "search", to: "index" },
	{ from: "search", to: "sql" },
	{ from: "booking", to: "sql" },
	{ from: "booking", to: "payment" },
	{ from: "sql", to: "relay" },
	{ from: "relay", to: "log" },
	{ from: "log", to: "guestread" },
	{ from: "log", to: "notify" },
	{ from: "trips", to: "guestread" },
];
